/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/resourcemgt/resource-name-editor.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/forms/src/directives/default_value_accessor';
import * as import12 from '@angular/forms/src/directives/ng_model';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/forms/src/directives/control_value_accessor';
import * as import15 from '@angular/forms/src/directives/ng_control';
var renderType_ResourceNameEditorComponent_Host:import0.RenderComponentType = (null as any);
class _View_ResourceNameEditorComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ResourceNameEditorComponent_0_4:import3.ResourceNameEditorComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceNameEditorComponent_Host0,renderType_ResourceNameEditorComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('resource-name-editor',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ResourceNameEditorComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ResourceNameEditorComponent_0_4 = new import3.ResourceNameEditorComponent(new import8.ElementRef(this._el_0));
    this._appEl_0.initComponent(this._ResourceNameEditorComponent_0_4,[],compView_0);
    compView_0.create(this._ResourceNameEditorComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ResourceNameEditorComponent) && (0 === requestNodeIndex))) { return this._ResourceNameEditorComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ResourceNameEditorComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ResourceNameEditorComponent_Host === (null as any))) { (renderType_ResourceNameEditorComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ResourceNameEditorComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ResourceNameEditorComponentNgFactory:import10.ComponentFactory<import3.ResourceNameEditorComponent> = new import10.ComponentFactory<import3.ResourceNameEditorComponent>('resource-name-editor',viewFactory_ResourceNameEditorComponent_Host0,import3.ResourceNameEditorComponent);
const styles_ResourceNameEditorComponent:any[] = [];
var renderType_ResourceNameEditorComponent:import0.RenderComponentType = (null as any);
class _View_ResourceNameEditorComponent0 extends import1.AppView<import3.ResourceNameEditorComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import11.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_23_4:any[];
  _NgModel_23_5:import12.NgModel;
  _NgControl_23_6:any;
  _NgControlStatus_23_7:import13.NgControlStatus;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import11.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_34_4:any[];
  _NgModel_34_5:import12.NgModel;
  _NgControl_34_6:any;
  _NgControlStatus_34_7:import13.NgControlStatus;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _DefaultValueAccessor_45_3:import11.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_45_4:any[];
  _NgModel_45_5:import12.NgModel;
  _NgControl_45_6:any;
  _NgControlStatus_45_7:import13.NgControlStatus;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_34:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceNameEditorComponent0,renderType_ResourceNameEditorComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','modal');
    this.renderer.setElementAttribute(this._el_0,'id','resource-name-editor');
    this.renderer.setElementAttribute(this._el_0,'role','dialog');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modal-content');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','modal-header');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'h2',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Edit resource name',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','modal-body');
    this._text_13 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','form-horizontal');
    this._text_15 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-group');
    this._text_17 = this.renderer.createText(this._el_16,'\n                        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'label',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','col-sm-3 control-label');
    this.renderer.setElementAttribute(this._el_18,'for','firstName');
    this._text_19 = this.renderer.createText(this._el_18,'First name',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n                        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','col-sm-7');
    this._text_22 = this.renderer.createText(this._el_21,'\n                            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'input',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','form-control');
    this.renderer.setElementAttribute(this._el_23,'id','firstName');
    this.renderer.setElementAttribute(this._el_23,'name','firstName');
    this.renderer.setElementAttribute(this._el_23,'type','text');
    this._DefaultValueAccessor_23_3 = new import11.DefaultValueAccessor(this.renderer,new import8.ElementRef(this._el_23));
    this._NG_VALUE_ACCESSOR_23_4 = [this._DefaultValueAccessor_23_3];
    this._NgModel_23_5 = new import12.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_23_4);
    this._NgControl_23_6 = this._NgModel_23_5;
    this._NgControlStatus_23_7 = new import13.NgControlStatus(this._NgControl_23_6);
    this._text_24 = this.renderer.createText(this._el_21,'\n                        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_14,'\n\n                    ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','form-group');
    this._text_28 = this.renderer.createText(this._el_27,'\n                        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'label',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','col-sm-3 control-label');
    this.renderer.setElementAttribute(this._el_29,'for','middleName');
    this._text_30 = this.renderer.createText(this._el_29,'Middle name',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n                        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_27,'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','col-sm-7');
    this._text_33 = this.renderer.createText(this._el_32,'\n                            ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','form-control');
    this.renderer.setElementAttribute(this._el_34,'id','middleName');
    this.renderer.setElementAttribute(this._el_34,'name','middleName');
    this.renderer.setElementAttribute(this._el_34,'type','text');
    this._DefaultValueAccessor_34_3 = new import11.DefaultValueAccessor(this.renderer,new import8.ElementRef(this._el_34));
    this._NG_VALUE_ACCESSOR_34_4 = [this._DefaultValueAccessor_34_3];
    this._NgModel_34_5 = new import12.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_4);
    this._NgControl_34_6 = this._NgModel_34_5;
    this._NgControlStatus_34_7 = new import13.NgControlStatus(this._NgControl_34_6);
    this._text_35 = this.renderer.createText(this._el_32,'\n                        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._text_37 = this.renderer.createText(this._el_14,'\n\n                    ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','form-group');
    this._text_39 = this.renderer.createText(this._el_38,'\n                        ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'label',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','col-sm-3 control-label');
    this.renderer.setElementAttribute(this._el_40,'for','lastName');
    this._text_41 = this.renderer.createText(this._el_40,'Last name',(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n                        ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_38,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','col-sm-7');
    this._text_44 = this.renderer.createText(this._el_43,'\n                            ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'input',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','form-control');
    this.renderer.setElementAttribute(this._el_45,'id','lastName');
    this.renderer.setElementAttribute(this._el_45,'name','lastName');
    this.renderer.setElementAttribute(this._el_45,'type','text');
    this._DefaultValueAccessor_45_3 = new import11.DefaultValueAccessor(this.renderer,new import8.ElementRef(this._el_45));
    this._NG_VALUE_ACCESSOR_45_4 = [this._DefaultValueAccessor_45_3];
    this._NgModel_45_5 = new import12.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_45_4);
    this._NgControl_45_6 = this._NgModel_45_5;
    this._NgControlStatus_45_7 = new import13.NgControlStatus(this._NgControl_45_6);
    this._text_46 = this.renderer.createText(this._el_43,'\n                        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_38,'\n                    ',(null as any));
    this._text_48 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_49 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_50 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','modal-footer');
    this._text_52 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'button',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_53,'type','button');
    this._text_54 = this.renderer.createText(this._el_53,'Ok',(null as any));
    this._text_55 = this.renderer.createText(this._el_51,'\n                ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_51,'button',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_56,'type','button');
    this._text_57 = this.renderer.createText(this._el_56,'Cancel',(null as any));
    this._text_58 = this.renderer.createText(this._el_51,'\n            ',(null as any));
    this._text_59 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_60 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_61 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_23,'ngModelChange',this.eventHandler(this._handle_ngModelChange_23_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_23,'input',this.eventHandler(this._handle_input_23_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_23,'blur',this.eventHandler(this._handle_blur_23_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_23_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_23_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_34,'ngModelChange',this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_34,'input',this.eventHandler(this._handle_input_34_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_34,'blur',this.eventHandler(this._handle_blur_34_2.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_34_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_45,'ngModelChange',this.eventHandler(this._handle_ngModelChange_45_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_45,'input',this.eventHandler(this._handle_input_45_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_45,'blur',this.eventHandler(this._handle_blur_45_2.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_45_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_45_0.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_53,'click',this.eventHandler(this._handle_click_53_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_56,'click',this.eventHandler(this._handle_click_56_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3; }
    if (((token === import14.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_4; }
    if (((token === import12.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_5; }
    if (((token === import15.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_6; }
    if (((token === import13.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_7; }
    if (((token === import11.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3; }
    if (((token === import14.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_4; }
    if (((token === import12.NgModel) && (34 === requestNodeIndex))) { return this._NgModel_34_5; }
    if (((token === import15.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_6; }
    if (((token === import13.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_7; }
    if (((token === import11.DefaultValueAccessor) && (45 === requestNodeIndex))) { return this._DefaultValueAccessor_45_3; }
    if (((token === import14.NG_VALUE_ACCESSOR) && (45 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_45_4; }
    if (((token === import12.NgModel) && (45 === requestNodeIndex))) { return this._NgModel_45_5; }
    if (((token === import15.NgControl) && (45 === requestNodeIndex))) { return this._NgControl_45_6; }
    if (((token === import13.NgControlStatus) && (45 === requestNodeIndex))) { return this._NgControlStatus_45_7; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = 'firstName';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgModel_23_5.name = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.name.firstName;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgModel_23_5.model = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgModel_23_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_14:any = 'middleName';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_34_5.name = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.name.middleName;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgModel_34_5.model = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._NgModel_34_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_25:any = 'lastName';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgModel_45_5.name = currVal_25;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_25,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this.context.name.lastName;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgModel_45_5.model = currVal_26;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    if ((changes !== (null as any))) { this._NgModel_45_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_5:any = this._NgControlStatus_23_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_23,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_23_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_23,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_23_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_23,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_23_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_23,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_23_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_23,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_23_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_16:any = this._NgControlStatus_34_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_34_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_34_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_34_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_34_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_34_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_27:any = this._NgControlStatus_45_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_45,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_45_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_45,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_45_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_45,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_45_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_45,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_45_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_45,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_45_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_45,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_34:boolean = !this.context.canOk;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementProperty(this._el_53,'disabled',currVal_34);
      this._expr_34 = currVal_34;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_23_5.ngOnDestroy();
    this._NgModel_34_5.ngOnDestroy();
    this._NgModel_45_5.ngOnDestroy();
  }
  private _handle_ngModelChange_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.name.firstName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_23_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_23_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_23_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_23_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.name.middleName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_34_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_34_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.name.lastName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_45_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_45_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_45_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_45_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_53_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.ok()) !== false);
    return (true && pd_0);
  }
  private _handle_click_56_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.cancel()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ResourceNameEditorComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ResourceNameEditorComponent> {
  if ((renderType_ResourceNameEditorComponent === (null as any))) { (renderType_ResourceNameEditorComponent = viewUtils.createRenderComponentType('C:/Workspace/Frameworks/temphire.angular2/TempHire/app/resourcemgt/resource-name-editor.html',0,import9.ViewEncapsulation.None,styles_ResourceNameEditorComponent,{})); }
  return new _View_ResourceNameEditorComponent0(viewUtils,parentInjector,declarationEl);
}