/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/resourcemgt/resource-mgt.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/resourcemgt/resource-mgt-unit-of-work';
import * as import9 from '../../../app/core/services/busy.service';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/router/src/router_state';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../../app/shared/directives/scroll-to-top.directive';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from '@angular/router/src/directives/router_outlet';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '@angular/router/src/router_outlet_map';
import * as import20 from '@angular/core/src/linker/component_factory_resolver';
import * as import21 from '@angular/common/src/directives/ng_class';
import * as import22 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import23 from '@angular/core/src/linker/element_ref';
var renderType_ResourceMgtComponent_Host:import0.RenderComponentType = (null as any);
class _View_ResourceMgtComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ResourceMgtComponent_0_4:import3.ResourceMgtComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceMgtComponent_Host0,renderType_ResourceMgtComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ResourceMgtComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ResourceMgtComponent_0_4 = new import3.ResourceMgtComponent(this.parentInjector.get(import8.ResourceMgtUnitOfWork),this.parentInjector.get(import9.BusyService),this.parentInjector.get(import10.Router),this.parentInjector.get(import11.ActivatedRoute));
    this._appEl_0.initComponent(this._ResourceMgtComponent_0_4,[],compView_0);
    compView_0.create(this._ResourceMgtComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ResourceMgtComponent) && (0 === requestNodeIndex))) { return this._ResourceMgtComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ResourceMgtComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._ResourceMgtComponent_0_4.ngOnDestroy();
  }
}
function viewFactory_ResourceMgtComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ResourceMgtComponent_Host === (null as any))) { (renderType_ResourceMgtComponent_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_ResourceMgtComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ResourceMgtComponentNgFactory:import13.ComponentFactory<import3.ResourceMgtComponent> = new import13.ComponentFactory<import3.ResourceMgtComponent>('ng-component',viewFactory_ResourceMgtComponent_Host0,import3.ResourceMgtComponent);
const styles_ResourceMgtComponent:any[] = [];
var renderType_ResourceMgtComponent:import0.RenderComponentType = (null as any);
class _View_ResourceMgtComponent0 extends import1.AppView<import3.ResourceMgtComponent> {
  _el_0:any;
  _ScrollToTopDirective_0_3:import14.ScrollToTopDirective;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _TemplateRef_33_5:any;
  _NgFor_33_6:import15.NgFor;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _RouterOutlet_38_5:import16.RouterOutlet;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceMgtComponent0,renderType_ResourceMgtComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','table-responsive');
    this.renderer.setElementAttribute(this._el_0,'scrollToTop','');
    this.renderer.setElementAttribute(this._el_0,'style','height: 220px; overflow: auto');
    this._ScrollToTopDirective_0_3 = new import14.ScrollToTopDirective();
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'table',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','table table-striped table-hover table-bordered');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'thead',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'tr',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'th',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Name',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'th',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Address 1',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_6,'th',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Address 2',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_6,'th',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'City',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_6,'th',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'State',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_6,'th',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Zipcode',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_6,'th',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Phone',(null as any));
    this._text_28 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_2,'tbody',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_31,(null as any));
    this._appEl_33 = new import2.AppElement(33,31,this,this._anchor_33);
    this._TemplateRef_33_5 = new import17.TemplateRef_(this._appEl_33,viewFactory_ResourceMgtComponent1);
    this._NgFor_33_6 = new import15.NgFor(this._appEl_33.vcRef,this._TemplateRef_33_5,this.parentInjector.get(import18.IterableDiffers),this.ref);
    this._text_34 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._text_35 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_37 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_38 = this.renderer.createElement(parentRenderNode,'router-outlet',(null as any));
    this._appEl_38 = new import2.AppElement(38,(null as any),this,this._el_38);
    this._RouterOutlet_38_5 = new import16.RouterOutlet(this.parentInjector.get(import19.RouterOutletMap),this._appEl_38.vcRef,this.parentInjector.get(import20.ComponentFactoryResolver),(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import15.NgFor) && (33 === requestNodeIndex))) { return this._NgFor_33_6; }
    if (((token === import14.ScrollToTopDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._ScrollToTopDirective_0_3; }
    if (((token === import16.RouterOutlet) && (38 === requestNodeIndex))) { return this._RouterOutlet_38_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScrollToTopDirective_0_3.ngOnInit(); }
    changes = (null as any);
    const currVal_0:any = this.context.staffingResources;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_33_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_33_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_33_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_38_5.ngOnDestroy();
  }
}
export function viewFactory_ResourceMgtComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ResourceMgtComponent> {
  if ((renderType_ResourceMgtComponent === (null as any))) { (renderType_ResourceMgtComponent = viewUtils.createRenderComponentType('C:/Workspace/Frameworks/temphire.angular2/TempHire/app/resourcemgt/resource-mgt.html',0,import12.ViewEncapsulation.None,styles_ResourceMgtComponent,{})); }
  return new _View_ResourceMgtComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceMgtComponent1 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import21.NgClass;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_1:any;
  _map_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceMgtComponent1,renderType_ResourceMgtComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','selectable');
    this._NgClass_0_3 = new import21.NgClass(this.parent.parentInjector.get(import18.IterableDiffers),this.parent.parentInjector.get(import22.KeyValueDiffers),new import23.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {info: p0};
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgClass_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'selectable';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_0_3.klass = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._map_0((this.context.$implicit.id == this.parent.context.staffingResourceId));
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_0_3.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.fullName,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.$implicit.address1,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_6,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.$implicit.address2,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_9,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.context.$implicit.city,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_12,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'',this.context.$implicit.state,'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_15,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'',this.context.$implicit.zipcode,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_18,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.$implicit.phoneNumber,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_21,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onSelect(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ResourceMgtComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceMgtComponent1(viewUtils,parentInjector,declarationEl);
}