/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/resourcemgt/resource-mgt-unit-of-work';
import * as import4 from '../../../app/resourcemgt/resource-detail.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../../../app/core/services/entity-manager-provider';
import * as import10 from '../../../app/core/services/busy.service';
import * as import11 from '@angular/router/src/router_state';
import * as import12 from '../../../app/core/services/dialog.service';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '../../../app/resourcemgt/resource-name-editor.component';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from './resource-name-editor.component.ngfactory';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/forms/src/directives/default_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_model';
import * as import23 from '@angular/forms/src/directives/ng_control_status';
import * as import24 from '../../../app/shared/controls/tab-container.component';
import * as import25 from '../../../app/shared/controls/tab-pane.directive';
import * as import26 from '../shared/controls/tab-container.component.ngfactory';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_control';
import * as import29 from '../../../app/resourcemgt/resource-contacts.component';
import * as import30 from './resource-contacts.component.ngfactory';
var renderType_ResourceDetailComponent_Host:import0.RenderComponentType = (null as any);
class _View_ResourceDetailComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ResourceMgtUnitOfWork_0_4:import3.ResourceMgtUnitOfWork;
  _ResourceDetailComponent_0_5:import4.ResourceDetailComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceDetailComponent_Host0,renderType_ResourceDetailComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ResourceDetailComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ResourceMgtUnitOfWork_0_4 = new import3.ResourceMgtUnitOfWork(this.parentInjector.get(import9.EntityManagerProvider));
    this._ResourceDetailComponent_0_5 = new import4.ResourceDetailComponent(this._ResourceMgtUnitOfWork_0_4,this.parentInjector.get(import10.BusyService),this.parentInjector.get(import11.ActivatedRoute),this.parentInjector.get(import12.DialogService));
    this._appEl_0.initComponent(this._ResourceDetailComponent_0_5,[],compView_0);
    compView_0.create(this._ResourceDetailComponent_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ResourceMgtUnitOfWork) && (0 === requestNodeIndex))) { return this._ResourceMgtUnitOfWork_0_4; }
    if (((token === import4.ResourceDetailComponent) && (0 === requestNodeIndex))) { return this._ResourceDetailComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ResourceDetailComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ResourceDetailComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ResourceDetailComponent_Host === (null as any))) { (renderType_ResourceDetailComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_ResourceDetailComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ResourceDetailComponentNgFactory:import14.ComponentFactory<import4.ResourceDetailComponent> = new import14.ComponentFactory<import4.ResourceDetailComponent>('ng-component',viewFactory_ResourceDetailComponent_Host0,import4.ResourceDetailComponent);
const styles_ResourceDetailComponent:any[] = [];
var renderType_ResourceDetailComponent:import0.RenderComponentType = (null as any);
class _View_ResourceDetailComponent0 extends import1.AppView<import4.ResourceDetailComponent> {
  _viewQuery_ResourceNameEditorComponent_0:import15.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import16.NgIf;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ResourceNameEditorComponent_4_4:import17.ResourceNameEditorComponent;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceDetailComponent0,renderType_ResourceDetailComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_ResourceNameEditorComponent_0 = new import15.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'hr',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this._appEl_2,viewFactory_ResourceDetailComponent1);
    this._NgIf_2_6 = new import16.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'resource-name-editor',(null as any));
    this._appEl_4 = new import2.AppElement(4,(null as any),this,this._el_4);
    var compView_4:any = import19.viewFactory_ResourceNameEditorComponent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ResourceNameEditorComponent_4_4 = new import17.ResourceNameEditorComponent(new import20.ElementRef(this._el_4));
    this._appEl_4.initComponent(this._ResourceNameEditorComponent_4_4,[],compView_4);
    compView_4.create(this._ResourceNameEditorComponent_4_4,[],(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._viewQuery_ResourceNameEditorComponent_0.reset([this._ResourceNameEditorComponent_4_4]);
    this.context.nameEditor = this._viewQuery_ResourceNameEditorComponent_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import17.ResourceNameEditorComponent) && (4 === requestNodeIndex))) { return this._ResourceNameEditorComponent_4_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.model;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.model;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ResourceNameEditorComponent_4_4.model = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ResourceDetailComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.ResourceDetailComponent> {
  if ((renderType_ResourceDetailComponent === (null as any))) { (renderType_ResourceDetailComponent = viewUtils.createRenderComponentType('C:/Workspace/Frameworks/temphire.angular2/TempHire/app/resourcemgt/resource-detail.html',0,import13.ViewEncapsulation.None,styles_ResourceDetailComponent,{})); }
  return new _View_ResourceDetailComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceDetailComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _DefaultValueAccessor_18_3:import21.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_18_4:any[];
  _NgModel_18_5:import22.NgModel;
  _NgControl_18_6:any;
  _NgControlStatus_18_7:import23.NgControlStatus;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TabContainer_24_4:import24.TabContainer;
  _query_TabPane_24_0:import15.QueryList<any>;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _TabPane_26_6:import25.TabPane;
  _query_self_26_0:import15.QueryList<any>;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _TabPane_28_6:import25.TabPane;
  _query_self_28_0:import15.QueryList<any>;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _TemplateRef_30_5:any;
  _TabPane_30_6:import25.TabPane;
  _query_self_30_0:import15.QueryList<any>;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _TemplateRef_32_5:any;
  _TabPane_32_6:import25.TabPane;
  _query_self_32_0:import15.QueryList<any>;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_24:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceDetailComponent1,renderType_ResourceDetailComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','detail');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn-group');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','btn btn-primary');
    this._el_5 = this.renderer.createElement(this._el_4,'i',(null as any));
    this.renderer.setElementAttribute(this._el_5,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_5,'class','fa fa-floppy-o');
    this._text_6 = this.renderer.createText(this._el_4,' Save',(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_2,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_8,'style','margin-left: 15px');
    this._el_9 = this.renderer.createElement(this._el_8,'i',(null as any));
    this.renderer.setElementAttribute(this._el_9,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_9,'class','fa fa-undo');
    this._text_10 = this.renderer.createText(this._el_8,' Cancel',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'h2',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','btn btn-default bt-lg');
    this.renderer.setElementAttribute(this._el_15,'style','margin-top: -5px');
    this.renderer.setElementAttribute(this._el_15,'title','Edit...');
    this._el_16 = this.renderer.createElement(this._el_15,'i',(null as any));
    this.renderer.setElementAttribute(this._el_16,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_16,'class','fa fa-pencil');
    this._text_17 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_0,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','form-control');
    this.renderer.setElementAttribute(this._el_18,'rows','5');
    this._DefaultValueAccessor_18_3 = new import21.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_18));
    this._NG_VALUE_ACCESSOR_18_4 = [this._DefaultValueAccessor_18_3];
    this._NgModel_18_5 = new import22.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_18_4);
    this._NgControl_18_6 = this._NgModel_18_5;
    this._NgControlStatus_18_7 = new import23.NgControlStatus(this._NgControl_18_6);
    this._text_19 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','panel');
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'style','margin-top: 15px');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'tab-container',(null as any));
    this._appEl_24 = new import2.AppElement(24,22,this,this._el_24);
    var compView_24:any = import26.viewFactory_TabContainer0(this.viewUtils,this.injector(24),this._appEl_24);
    this._TabContainer_24_4 = new import24.TabContainer();
    this._query_TabPane_24_0 = new import15.QueryList<any>();
    this._appEl_24.initComponent(this._TabContainer_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_26 = new import2.AppElement(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import18.TemplateRef_(this._appEl_26,viewFactory_ResourceDetailComponent2);
    this._TabPane_26_6 = new import25.TabPane(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._query_self_26_0 = new import15.QueryList<any>();
    this._query_self_26_0.reset([]);
    this._TabPane_26_6.component = this._query_self_26_0.first;
    this._text_27 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_28 = new import2.AppElement(28,24,this,this._anchor_28);
    this._TemplateRef_28_5 = new import18.TemplateRef_(this._appEl_28,viewFactory_ResourceDetailComponent3);
    this._TabPane_28_6 = new import25.TabPane(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._query_self_28_0 = new import15.QueryList<any>();
    this._query_self_28_0.reset([]);
    this._TabPane_28_6.component = this._query_self_28_0.first;
    this._text_29 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_30 = new import2.AppElement(30,24,this,this._anchor_30);
    this._TemplateRef_30_5 = new import18.TemplateRef_(this._appEl_30,viewFactory_ResourceDetailComponent4);
    this._TabPane_30_6 = new import25.TabPane(this._appEl_30.vcRef,this._TemplateRef_30_5);
    this._query_self_30_0 = new import15.QueryList<any>();
    this._query_self_30_0.reset([]);
    this._TabPane_30_6.component = this._query_self_30_0.first;
    this._text_31 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_32 = new import2.AppElement(32,24,this,this._anchor_32);
    this._TemplateRef_32_5 = new import18.TemplateRef_(this._appEl_32,viewFactory_ResourceDetailComponent5);
    this._TabPane_32_6 = new import25.TabPane(this._appEl_32.vcRef,this._TemplateRef_32_5);
    this._query_self_32_0 = new import15.QueryList<any>();
    this._query_self_32_0.reset([]);
    this._TabPane_32_6.component = this._query_self_32_0.first;
    this._text_33 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_24.create(this._TabContainer_24_4,[[].concat([
        this._text_25,
        this._appEl_26,
        this._text_27,
        this._appEl_28,
        this._text_29,
        this._appEl_30,
        this._text_31,
        this._appEl_32,
        this._text_33
      ]
    )],(null as any));
    this._text_34 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_35 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','btn-group');
    this._text_38 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','btn btn-primary');
    this._el_40 = this.renderer.createElement(this._el_39,'i',(null as any));
    this.renderer.setElementAttribute(this._el_40,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_40,'class','fa fa-floppy-o');
    this._text_41 = this.renderer.createText(this._el_39,' Save',(null as any));
    this._text_42 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_37,'button',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_43,'style','margin-left: 15px');
    this._el_44 = this.renderer.createElement(this._el_43,'i',(null as any));
    this.renderer.setElementAttribute(this._el_44,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_44,'class','fa fa-undo');
    this._text_45 = this.renderer.createText(this._el_43,' Cancel',(null as any));
    this._text_46 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._text_47 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_1 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_4 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_18,'ngModelChange',this.eventHandler(this._handle_ngModelChange_18_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_18,'input',this.eventHandler(this._handle_input_18_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_18,'blur',this.eventHandler(this._handle_blur_18_2.bind(this)));
    this._expr_9 = import8.UNINITIALIZED;
    const subscription_0:any = this._NgModel_18_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_18_0.bind(this)));
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    this._expr_24 = import8.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_43,'click',this.eventHandler(this._handle_click_43_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.DefaultValueAccessor) && (18 === requestNodeIndex))) { return this._DefaultValueAccessor_18_3; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (18 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_18_4; }
    if (((token === import22.NgModel) && (18 === requestNodeIndex))) { return this._NgModel_18_5; }
    if (((token === import28.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_6; }
    if (((token === import23.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_7; }
    if (((token === import18.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import25.TabPane) && (26 === requestNodeIndex))) { return this._TabPane_26_6; }
    if (((token === import18.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import25.TabPane) && (28 === requestNodeIndex))) { return this._TabPane_28_6; }
    if (((token === import18.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import25.TabPane) && (30 === requestNodeIndex))) { return this._TabPane_30_6; }
    if (((token === import18.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import25.TabPane) && (32 === requestNodeIndex))) { return this._TabPane_32_6; }
    if (((token === import24.TabContainer) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._TabContainer_24_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_9:any = this.parent.context.model.summary;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgModel_18_5.model = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgModel_18_5.ngOnChanges(changes); }
    const currVal_16:any = 'Contact Info';
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._TabPane_26_6.title = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = 'true';
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._TabPane_26_6.active = currVal_17;
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = 'Rates';
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._TabPane_28_6.title = currVal_18;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = 'Work Experience';
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._TabPane_30_6.title = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = 'Skills';
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._TabPane_32_6.title = currVal_20;
      this._expr_20 = currVal_20;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_TabPane_24_0.dirty) {
      this._query_TabPane_24_0.reset([
        this._TabPane_26_6,
        this._TabPane_28_6,
        this._TabPane_30_6,
        this._TabPane_32_6
      ]
      );
      this._TabContainer_24_4.panes = this._query_TabPane_24_0;
      this._query_TabPane_24_0.notifyOnChanges();
    } }
    const currVal_1:boolean = !this.parent.context.canSave;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_4,'disabled',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:boolean = !this.parent.context.canSave;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_8,'disabled',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import5.interpolate(1,'',this.parent.context.model.fullName,' ');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_14,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_10:any = this._NgControlStatus_18_7.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_18_7.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_18_7.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_18_7.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_18_7.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_18_7.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_22:boolean = !this.parent.context.canSave;
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementProperty(this._el_39,'disabled',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_24:boolean = !this.parent.context.canSave;
    if (import5.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementProperty(this._el_43,'disabled',currVal_24);
      this._expr_24 = currVal_24;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_18_5.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.save()) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.cancel()) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.editName()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.model.summary = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_18_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_18_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_18_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_18_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.save()) !== false);
    return (true && pd_0);
  }
  private _handle_click_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.cancel()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ResourceDetailComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceDetailComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceDetailComponent2 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _ResourceContactsComponent_1_4:import29.ResourceContactsComponent;
  _text_2:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceDetailComponent2,renderType_ResourceDetailComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'resource-contacts',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import30.viewFactory_ResourceContactsComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._ResourceContactsComponent_1_4 = new import29.ResourceContactsComponent(this.parent.parentInjector.get(import3.ResourceMgtUnitOfWork));
    this._appEl_1.initComponent(this._ResourceContactsComponent_1_4,[],compView_1);
    compView_1.create(this._ResourceContactsComponent_1_4,[],(null as any));
    this._text_2 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.ResourceContactsComponent) && (1 === requestNodeIndex))) { return this._ResourceContactsComponent_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.parent.parent.context.model;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ResourceContactsComponent_1_4.model = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ResourceContactsComponent_1_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ResourceDetailComponent2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceDetailComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceDetailComponent3 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceDetailComponent3,renderType_ResourceDetailComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Placeholder...',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n                ',(null as any));
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_3
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ResourceDetailComponent3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceDetailComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceDetailComponent4 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceDetailComponent4,renderType_ResourceDetailComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Placeholder...',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n                ',(null as any));
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_3
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ResourceDetailComponent4(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceDetailComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceDetailComponent5 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceDetailComponent5,renderType_ResourceDetailComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_1 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Placeholder...',(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n                ',(null as any));
    this.init([].concat([
      this._text_0,
      this._el_1,
      this._text_3
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ResourceDetailComponent5(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceDetailComponent5(viewUtils,parentInjector,declarationEl);
}