/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../app/resourcemgt/resource-mgt.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '../../../app/shared/shared.module';
import * as import4 from '@angular/forms/src/directives';
import * as import5 from '@angular/forms/src/form_providers';
import * as import6 from '@angular/router/src/router_module';
import * as import7 from '@angular/common/src/localization';
import * as import8 from '../../../app/shared/services/unit-of-work';
import * as import9 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import10 from '../../../app/resourcemgt/resource-mgt-unit-of-work';
import * as import11 from '@angular/core/src/di/injector';
import * as import12 from './resource-mgt.component.ngfactory';
import * as import13 from './resource-detail.component.ngfactory';
import * as import14 from '../../../app/core/services/entity-manager-provider';
import * as import15 from '../../../app/resourcemgt/resource-mgt.component';
import * as import16 from '../../../app/core/services/guards';
import * as import17 from '../../../app/resourcemgt/resource-detail.component';
import * as import18 from '@angular/core/src/i18n/tokens';
import * as import19 from '@angular/router/src/router_config_loader';
class ResourceMgtModuleInjector extends import0.NgModuleInjector<import1.ResourceMgtModule> {
  _CommonModule_0:import2.CommonModule;
  _SharedModule_1:import3.SharedModule;
  _InternalFormsSharedModule_2:import4.InternalFormsSharedModule;
  _FormsModule_3:import5.FormsModule;
  _RouterModule_4:import6.RouterModule;
  _ResourceMgtModule_5:import1.ResourceMgtModule;
  __LOCALE_ID_6:any;
  __NgLocalization_7:import7.NgLocaleLocalization;
  __UnitOfWork_8:import8.UnitOfWork;
  __RadioControlRegistry_9:import9.RadioControlRegistry;
  __ROUTES_10:any[];
  __ResourceMgtUnitOfWork_11:import10.ResourceMgtUnitOfWork;
  __TRANSLATIONS_FORMAT_12:any;
  constructor(parent:import11.Injector) {
    super(parent,[
      import12.ResourceMgtComponentNgFactory,
      import12.ResourceMgtComponentNgFactory,
      import13.ResourceDetailComponentNgFactory
    ]
    ,[]);
  }
  get _LOCALE_ID_6():any {
    if ((this.__LOCALE_ID_6 == (null as any))) { (this.__LOCALE_ID_6 = (null as any)); }
    return this.__LOCALE_ID_6;
  }
  get _NgLocalization_7():import7.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == (null as any))) { (this.__NgLocalization_7 = new import7.NgLocaleLocalization(this._LOCALE_ID_6)); }
    return this.__NgLocalization_7;
  }
  get _UnitOfWork_8():import8.UnitOfWork {
    if ((this.__UnitOfWork_8 == (null as any))) { (this.__UnitOfWork_8 = new import8.UnitOfWork(this.parent.get(import14.EntityManagerProvider))); }
    return this.__UnitOfWork_8;
  }
  get _RadioControlRegistry_9():import9.RadioControlRegistry {
    if ((this.__RadioControlRegistry_9 == (null as any))) { (this.__RadioControlRegistry_9 = new import9.RadioControlRegistry()); }
    return this.__RadioControlRegistry_9;
  }
  get _ROUTES_10():any[] {
      if ((this.__ROUTES_10 == (null as any))) { (this.__ROUTES_10 = [[
        {
          path: 'resourcemgt',
          component: import15.ResourceMgtComponent,
          canActivate: [import16.PrepareGuard]
        }
        ,
        {
          path: 'resourcemgt',
          component: import15.ResourceMgtComponent,
          canActivate: [import16.PrepareGuard],
            children: [{
              path: ':id',
              component: import17.ResourceDetailComponent,
              canDeactivate: [import16.CanDeactivateGuard]
            }
          ]
        }

      ]
    ]); }
    return this.__ROUTES_10;
  }
  get _ResourceMgtUnitOfWork_11():import10.ResourceMgtUnitOfWork {
    if ((this.__ResourceMgtUnitOfWork_11 == (null as any))) { (this.__ResourceMgtUnitOfWork_11 = new import10.ResourceMgtUnitOfWork(this.parent.get(import14.EntityManagerProvider))); }
    return this.__ResourceMgtUnitOfWork_11;
  }
  get _TRANSLATIONS_FORMAT_12():any {
    if ((this.__TRANSLATIONS_FORMAT_12 == (null as any))) { (this.__TRANSLATIONS_FORMAT_12 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_12;
  }
  createInternal():import1.ResourceMgtModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._SharedModule_1 = new import3.SharedModule();
    this._InternalFormsSharedModule_2 = new import4.InternalFormsSharedModule();
    this._FormsModule_3 = new import5.FormsModule();
    this._RouterModule_4 = new import6.RouterModule(this.parent.get(import6.ROUTER_FORROOT_GUARD,(null as any)));
    this._ResourceMgtModule_5 = new import1.ResourceMgtModule();
    return this._ResourceMgtModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.SharedModule)) { return this._SharedModule_1; }
    if ((token === import4.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_2; }
    if ((token === import5.FormsModule)) { return this._FormsModule_3; }
    if ((token === import6.RouterModule)) { return this._RouterModule_4; }
    if ((token === import1.ResourceMgtModule)) { return this._ResourceMgtModule_5; }
    if ((token === import18.LOCALE_ID)) { return this._LOCALE_ID_6; }
    if ((token === import7.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import8.UnitOfWork)) { return this._UnitOfWork_8; }
    if ((token === import9.RadioControlRegistry)) { return this._RadioControlRegistry_9; }
    if ((token === import19.ROUTES)) { return this._ROUTES_10; }
    if ((token === import10.ResourceMgtUnitOfWork)) { return this._ResourceMgtUnitOfWork_11; }
    if ((token === import18.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_12; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ResourceMgtModuleNgFactory:import0.NgModuleFactory<import1.ResourceMgtModule> = new import0.NgModuleFactory(ResourceMgtModuleInjector,import1.ResourceMgtModule);