/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/resourcemgt/resource-contacts.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/resourcemgt/resource-mgt-unit-of-work';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/common/src/directives/ng_for';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import14 from '@angular/common/src/directives/ng_class';
import * as import15 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/default_value_accessor';
import * as import18 from '@angular/forms/src/directives/ng_model';
import * as import19 from '@angular/forms/src/directives/ng_control_status';
import * as import20 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
var renderType_ResourceContactsComponent_Host:import0.RenderComponentType = (null as any);
class _View_ResourceContactsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ResourceContactsComponent_0_4:import3.ResourceContactsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceContactsComponent_Host0,renderType_ResourceContactsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('resource-contacts',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ResourceContactsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ResourceContactsComponent_0_4 = new import3.ResourceContactsComponent(this.parentInjector.get(import8.ResourceMgtUnitOfWork));
    this._appEl_0.initComponent(this._ResourceContactsComponent_0_4,[],compView_0);
    compView_0.create(this._ResourceContactsComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ResourceContactsComponent) && (0 === requestNodeIndex))) { return this._ResourceContactsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ResourceContactsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ResourceContactsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ResourceContactsComponent_Host === (null as any))) { (renderType_ResourceContactsComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ResourceContactsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ResourceContactsComponentNgFactory:import10.ComponentFactory<import3.ResourceContactsComponent> = new import10.ComponentFactory<import3.ResourceContactsComponent>('resource-contacts',viewFactory_ResourceContactsComponent_Host0,import3.ResourceContactsComponent);
const styles_ResourceContactsComponent:any[] = [];
var renderType_ResourceContactsComponent:import0.RenderComponentType = (null as any);
class _View_ResourceContactsComponent0 extends import1.AppView<import3.ResourceContactsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _TemplateRef_20_5:any;
  _NgFor_20_6:import11.NgFor;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _TemplateRef_32_5:any;
  _NgFor_32_6:import11.NgFor;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _anchor_51:any;
  /*private*/ _appEl_51:import2.AppElement;
  _TemplateRef_51_5:any;
  _NgFor_51_6:import11.NgFor;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _anchor_63:any;
  /*private*/ _appEl_63:import2.AppElement;
  _TemplateRef_63_5:any;
  _NgFor_63_6:import11.NgFor;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceContactsComponent0,renderType_ResourceContactsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container-fluid');
    this.renderer.setElementAttribute(this._el_0,'style','margin-top: 10px');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','col-sm-6');
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','row');
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-sm-1');
    this._text_10 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','btn-group');
    this.renderer.setElementAttribute(this._el_11,'style','margin-top: 4px');
    this._text_12 = this.renderer.createText(this._el_11,'\n                        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','btn btn-success dropdown-toggle btn-sm');
    this.renderer.setElementAttribute(this._el_13,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_13,'title','New...');
    this.renderer.setElementAttribute(this._el_13,'type','button');
    this._text_14 = this.renderer.createText(this._el_13,'\n                            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'span',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','caret');
    this._text_16 = this.renderer.createText(this._el_13,'\n                        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_11,'\n                        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_11,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','dropdown-menu');
    this.renderer.setElementAttribute(this._el_18,'role','menu');
    this._text_19 = this.renderer.createText(this._el_18,'\n                            ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_20 = new import2.AppElement(20,18,this,this._anchor_20);
    this._TemplateRef_20_5 = new import12.TemplateRef_(this._appEl_20,viewFactory_ResourceContactsComponent1);
    this._NgFor_20_6 = new import11.NgFor(this._appEl_20.vcRef,this._TemplateRef_20_5,this.parentInjector.get(import13.IterableDiffers),this.ref);
    this._text_21 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','col-sm-11');
    this._text_26 = this.renderer.createText(this._el_25,'\n                    ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'h4',(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Addresses',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._text_30 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_32 = new import2.AppElement(32,5,this,this._anchor_32);
    this._TemplateRef_32_5 = new import12.TemplateRef_(this._appEl_32,viewFactory_ResourceContactsComponent2);
    this._NgFor_32_6 = new import11.NgFor(this._appEl_32.vcRef,this._TemplateRef_32_5,this.parentInjector.get(import13.IterableDiffers),this.ref);
    this._text_33 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_35 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','col-sm-6');
    this._text_37 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'div',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','row');
    this._text_39 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'div',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','col-sm-1');
    this._text_41 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'div',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','btn-group');
    this.renderer.setElementAttribute(this._el_42,'style','margin-top: 4px');
    this._text_43 = this.renderer.createText(this._el_42,'\n                        ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'button',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','btn btn-success dropdown-toggle btn-sm');
    this.renderer.setElementAttribute(this._el_44,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_44,'title','New...');
    this.renderer.setElementAttribute(this._el_44,'type','button');
    this._text_45 = this.renderer.createText(this._el_44,'\n                            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'span',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','caret');
    this._text_47 = this.renderer.createText(this._el_44,'\n                        ',(null as any));
    this._text_48 = this.renderer.createText(this._el_42,'\n                        ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_42,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','dropdown-menu');
    this.renderer.setElementAttribute(this._el_49,'role','menu');
    this._text_50 = this.renderer.createText(this._el_49,'\n                            ',(null as any));
    this._anchor_51 = this.renderer.createTemplateAnchor(this._el_49,(null as any));
    this._appEl_51 = new import2.AppElement(51,49,this,this._anchor_51);
    this._TemplateRef_51_5 = new import12.TemplateRef_(this._appEl_51,viewFactory_ResourceContactsComponent4);
    this._NgFor_51_6 = new import11.NgFor(this._appEl_51.vcRef,this._TemplateRef_51_5,this.parentInjector.get(import13.IterableDiffers),this.ref);
    this._text_52 = this.renderer.createText(this._el_49,'\n                        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_42,'\n                    ',(null as any));
    this._text_54 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_38,'div',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','col-sm-11');
    this._text_57 = this.renderer.createText(this._el_56,'\n                    ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_56,'h4',(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'Phone Numbers',(null as any));
    this._text_60 = this.renderer.createText(this._el_56,'\n                ',(null as any));
    this._text_61 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._text_62 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._anchor_63 = this.renderer.createTemplateAnchor(this._el_36,(null as any));
    this._appEl_63 = new import2.AppElement(63,36,this,this._anchor_63);
    this._TemplateRef_63_5 = new import12.TemplateRef_(this._appEl_63,viewFactory_ResourceContactsComponent5);
    this._NgFor_63_6 = new import11.NgFor(this._appEl_63.vcRef,this._TemplateRef_63_5,this.parentInjector.get(import13.IterableDiffers),this.ref);
    this._text_64 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._text_65 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_66 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_67 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._anchor_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._anchor_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import11.NgFor) && (20 === requestNodeIndex))) { return this._NgFor_20_6; }
    if (((token === import12.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import11.NgFor) && (32 === requestNodeIndex))) { return this._NgFor_32_6; }
    if (((token === import12.TemplateRef) && (51 === requestNodeIndex))) { return this._TemplateRef_51_5; }
    if (((token === import11.NgFor) && (51 === requestNodeIndex))) { return this._NgFor_51_6; }
    if (((token === import12.TemplateRef) && (63 === requestNodeIndex))) { return this._TemplateRef_63_5; }
    if (((token === import11.NgFor) && (63 === requestNodeIndex))) { return this._NgFor_63_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.addressTypes;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_20_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_20_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_20_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_1:any = this.context.model.addresses;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_32_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_32_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_32_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_2:any = this.context.phoneNumberTypes;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_51_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_51_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_51_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_3:any = this.context.model.phoneNumbers;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_63_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_63_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_63_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ResourceContactsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ResourceContactsComponent> {
  if ((renderType_ResourceContactsComponent === (null as any))) { (renderType_ResourceContactsComponent = viewUtils.createRenderComponentType('C:/Workspace/Frameworks/temphire.angular2/TempHire/app/resourcemgt/resource-contacts.html',0,import9.ViewEncapsulation.None,styles_ResourceContactsComponent,{})); }
  return new _View_ResourceContactsComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceContactsComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _NgClass_4_3:import14.NgClass;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_1:any;
  _map_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceContactsComponent1,renderType_ResourceContactsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','selectable');
    this._text_1 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'i',(null as any));
    this.renderer.setElementAttribute(this._el_4,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_4,'class','fa');
    this.renderer.setElementAttribute(this._el_4,'style','width: 20px; text-align: center');
    this._NgClass_4_3 = new import14.NgClass(this.parent.parentInjector.get(import13.IterableDiffers),this.parent.parentInjector.get(import15.KeyValueDiffers),new import16.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_4,'\n                                    ',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        'fa-envelope-o': p0,
        'fa-building-o': p1,
        'fa-home': p2
      }
      ;
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.NgClass) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._NgClass_4_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'fa';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_4_3.klass = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._map_0((this.context.$implicit.name == 'Mailing'),(this.context.$implicit.name == 'Work'),(this.context.$implicit.name == 'Home'));
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_4_3.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_4_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = import4.interpolate(1,'\n                                    New ',this.context.$implicit.displayName,'\n                                ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_6,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.addAddress(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ResourceContactsComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceContactsComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceContactsComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _DefaultValueAccessor_14_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_14_4:any[];
  _NgModel_14_5:import18.NgModel;
  _NgControl_14_6:any;
  _NgControlStatus_14_7:import19.NgControlStatus;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_25_4:any[];
  _NgModel_25_5:import18.NgModel;
  _NgControl_25_6:any;
  _NgControlStatus_25_7:import19.NgControlStatus;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _DefaultValueAccessor_36_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_36_4:any[];
  _NgModel_36_5:import18.NgModel;
  _NgControl_36_6:any;
  _NgControlStatus_36_7:import19.NgControlStatus;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _SelectControlValueAccessor_47_3:import20.SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_47_4:any[];
  _NgModel_47_5:import18.NgModel;
  _NgControl_47_6:any;
  _NgControlStatus_47_7:import19.NgControlStatus;
  _text_48:any;
  _anchor_49:any;
  /*private*/ _appEl_49:import2.AppElement;
  _TemplateRef_49_5:any;
  _NgFor_49_6:import11.NgFor;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _DefaultValueAccessor_61_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_61_4:any[];
  _NgModel_61_5:import18.NgModel;
  _NgControl_61_6:any;
  _NgControlStatus_61_7:import19.NgControlStatus;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_56:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceContactsComponent2,renderType_ResourceContactsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this.renderer.setElementAttribute(this._el_0,'style','margin-top: 20px');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-sm-10 form-horizontal');
    this._text_3 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h4',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','form-group');
    this._text_8 = this.renderer.createText(this._el_7,'\n                        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'label',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-sm-3 control-label');
    this._text_10 = this.renderer.createText(this._el_9,'Address 1',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n                        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','col-sm-9');
    this._text_13 = this.renderer.createText(this._el_12,'\n                            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'input',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','form-control');
    this.renderer.setElementAttribute(this._el_14,'placeholder','Address 1');
    this.renderer.setElementAttribute(this._el_14,'type','text');
    this._DefaultValueAccessor_14_3 = new import17.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_14));
    this._NG_VALUE_ACCESSOR_14_4 = [this._DefaultValueAccessor_14_3];
    this._NgModel_14_5 = new import18.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_14_4);
    this._NgControl_14_6 = this._NgModel_14_5;
    this._NgControlStatus_14_7 = new import19.NgControlStatus(this._NgControl_14_6);
    this._text_15 = this.renderer.createText(this._el_12,'\n                        ',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n                    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','form-group');
    this._text_19 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'label',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','col-sm-3 control-label');
    this._text_21 = this.renderer.createText(this._el_20,'Address 2',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','col-sm-9');
    this._text_24 = this.renderer.createText(this._el_23,'\n                            ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','form-control');
    this.renderer.setElementAttribute(this._el_25,'placeholder','Address 2');
    this.renderer.setElementAttribute(this._el_25,'type','text');
    this._DefaultValueAccessor_25_3 = new import17.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_25));
    this._NG_VALUE_ACCESSOR_25_4 = [this._DefaultValueAccessor_25_3];
    this._NgModel_25_5 = new import18.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_25_4);
    this._NgControl_25_6 = this._NgModel_25_5;
    this._NgControlStatus_25_7 = new import19.NgControlStatus(this._NgControl_25_6);
    this._text_26 = this.renderer.createText(this._el_23,'\n                        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-group');
    this._text_30 = this.renderer.createText(this._el_29,'\n                        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'label',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','col-sm-3 control-label');
    this._text_32 = this.renderer.createText(this._el_31,'City',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n                        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_29,'div',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','col-sm-9');
    this._text_35 = this.renderer.createText(this._el_34,'\n                            ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'input',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','form-control');
    this.renderer.setElementAttribute(this._el_36,'placeholder','City');
    this.renderer.setElementAttribute(this._el_36,'type','text');
    this._DefaultValueAccessor_36_3 = new import17.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_36));
    this._NG_VALUE_ACCESSOR_36_4 = [this._DefaultValueAccessor_36_3];
    this._NgModel_36_5 = new import18.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_36_4);
    this._NgControl_36_6 = this._NgModel_36_5;
    this._NgControlStatus_36_7 = new import19.NgControlStatus(this._NgControl_36_6);
    this._text_37 = this.renderer.createText(this._el_34,'\n                        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','form-group');
    this._text_41 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'label',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','col-sm-3 control-label');
    this._text_43 = this.renderer.createText(this._el_42,'State',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_40,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','col-sm-9');
    this._text_46 = this.renderer.createText(this._el_45,'\n                            ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'select',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','form-control');
    this._SelectControlValueAccessor_47_3 = new import20.SelectControlValueAccessor(this.renderer,new import16.ElementRef(this._el_47));
    this._NG_VALUE_ACCESSOR_47_4 = [this._SelectControlValueAccessor_47_3];
    this._NgModel_47_5 = new import18.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_47_4);
    this._NgControl_47_6 = this._NgModel_47_5;
    this._NgControlStatus_47_7 = new import19.NgControlStatus(this._NgControl_47_6);
    this._text_48 = this.renderer.createText(this._el_47,'\n                                ',(null as any));
    this._anchor_49 = this.renderer.createTemplateAnchor(this._el_47,(null as any));
    this._appEl_49 = new import2.AppElement(49,47,this,this._anchor_49);
    this._TemplateRef_49_5 = new import12.TemplateRef_(this._appEl_49,viewFactory_ResourceContactsComponent3);
    this._NgFor_49_6 = new import11.NgFor(this._appEl_49.vcRef,this._TemplateRef_49_5,this.parent.parentInjector.get(import13.IterableDiffers),this.parent.ref);
    this._text_50 = this.renderer.createText(this._el_47,'\n                            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_45,'\n                        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','form-group');
    this._text_55 = this.renderer.createText(this._el_54,'\n                        ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'label',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','col-sm-3 control-label');
    this._text_57 = this.renderer.createText(this._el_56,'Zipcode',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n                        ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_54,'div',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','col-sm-9');
    this._text_60 = this.renderer.createText(this._el_59,'\n                            ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'input',(null as any));
    this.renderer.setElementAttribute(this._el_61,'class','form-control');
    this.renderer.setElementAttribute(this._el_61,'placeholder','Zipcode');
    this.renderer.setElementAttribute(this._el_61,'type','text');
    this._DefaultValueAccessor_61_3 = new import17.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_61));
    this._NG_VALUE_ACCESSOR_61_4 = [this._DefaultValueAccessor_61_3];
    this._NgModel_61_5 = new import18.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_61_4);
    this._NgControl_61_6 = this._NgModel_61_5;
    this._NgControlStatus_61_7 = new import19.NgControlStatus(this._NgControl_61_6);
    this._text_62 = this.renderer.createText(this._el_59,'\n                        ',(null as any));
    this._text_63 = this.renderer.createText(this._el_54,'\n                    ',(null as any));
    this._text_64 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_65,'class','form-group');
    this._text_66 = this.renderer.createText(this._el_65,'\n                        ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_65,'div',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','col-sm-offset-3 col-sm-9');
    this._text_68 = this.renderer.createText(this._el_67,'\n                            ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_67,'div',(null as any));
    this.renderer.setElementAttribute(this._el_69,'class','checkbox');
    this._text_70 = this.renderer.createText(this._el_69,'\n                                ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_69,'label',(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'\n                                    ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_71,'input',(null as any));
    this.renderer.setElementAttribute(this._el_73,'type','checkbox');
    this._text_74 = this.renderer.createText(this._el_71,' Primary\n                                ',(null as any));
    this._text_75 = this.renderer.createText(this._el_69,'\n                            ',(null as any));
    this._text_76 = this.renderer.createText(this._el_67,'\n                        ',(null as any));
    this._text_77 = this.renderer.createText(this._el_65,'\n                    ',(null as any));
    this._text_78 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_79 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','col-sm-2');
    this._text_81 = this.renderer.createText(this._el_80,'\n                    ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'button',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','btn btn-danger');
    this.renderer.setElementAttribute(this._el_82,'style','margin-top:10px');
    this.renderer.setElementAttribute(this._el_82,'title','Delete...');
    this._el_83 = this.renderer.createElement(this._el_82,'i',(null as any));
    this.renderer.setElementAttribute(this._el_83,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_83,'class','fa fa-trash-o');
    this._text_84 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._text_85 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_14,'ngModelChange',this.eventHandler(this._handle_ngModelChange_14_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_14,'input',this.eventHandler(this._handle_input_14_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_14,'blur',this.eventHandler(this._handle_blur_14_2.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_14_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_14_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_25,'ngModelChange',this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_25,'input',this.eventHandler(this._handle_input_25_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_25,'blur',this.eventHandler(this._handle_blur_25_2.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_25_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_36,'ngModelChange',this.eventHandler(this._handle_ngModelChange_36_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_36,'input',this.eventHandler(this._handle_input_36_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_36,'blur',this.eventHandler(this._handle_blur_36_2.bind(this)));
    this._expr_24 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_36_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_36_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_47,'ngModelChange',this.eventHandler(this._handle_ngModelChange_47_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_47,'change',this.eventHandler(this._handle_change_47_1.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_47,'blur',this.eventHandler(this._handle_blur_47_2.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    const subscription_3:any = this._NgModel_47_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_47_0.bind(this)));
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_61,'ngModelChange',this.eventHandler(this._handle_ngModelChange_61_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_61,'input',this.eventHandler(this._handle_input_61_1.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_61,'blur',this.eventHandler(this._handle_blur_61_2.bind(this)));
    this._expr_45 = import7.UNINITIALIZED;
    const subscription_4:any = this._NgModel_61_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_61_0.bind(this)));
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    var disposable_15:Function = this.renderer.listen(this._el_73,'click',this.eventHandler(this._handle_click_73_0.bind(this)));
    this._expr_56 = import7.UNINITIALIZED;
    var disposable_16:Function = this.renderer.listen(this._el_82,'click',this.eventHandler(this._handle_click_82_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._anchor_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._el_83,
      this._text_84,
      this._text_85
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.DefaultValueAccessor) && (14 === requestNodeIndex))) { return this._DefaultValueAccessor_14_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (14 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_14_4; }
    if (((token === import18.NgModel) && (14 === requestNodeIndex))) { return this._NgModel_14_5; }
    if (((token === import22.NgControl) && (14 === requestNodeIndex))) { return this._NgControl_14_6; }
    if (((token === import19.NgControlStatus) && (14 === requestNodeIndex))) { return this._NgControlStatus_14_7; }
    if (((token === import17.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_4; }
    if (((token === import18.NgModel) && (25 === requestNodeIndex))) { return this._NgModel_25_5; }
    if (((token === import22.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_6; }
    if (((token === import19.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_7; }
    if (((token === import17.DefaultValueAccessor) && (36 === requestNodeIndex))) { return this._DefaultValueAccessor_36_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (36 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_36_4; }
    if (((token === import18.NgModel) && (36 === requestNodeIndex))) { return this._NgModel_36_5; }
    if (((token === import22.NgControl) && (36 === requestNodeIndex))) { return this._NgControl_36_6; }
    if (((token === import19.NgControlStatus) && (36 === requestNodeIndex))) { return this._NgControlStatus_36_7; }
    if (((token === import12.TemplateRef) && (49 === requestNodeIndex))) { return this._TemplateRef_49_5; }
    if (((token === import11.NgFor) && (49 === requestNodeIndex))) { return this._NgFor_49_6; }
    if (((token === import20.SelectControlValueAccessor) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._SelectControlValueAccessor_47_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NG_VALUE_ACCESSOR_47_4; }
    if (((token === import18.NgModel) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgModel_47_5; }
    if (((token === import22.NgControl) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgControl_47_6; }
    if (((token === import19.NgControlStatus) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgControlStatus_47_7; }
    if (((token === import17.DefaultValueAccessor) && (61 === requestNodeIndex))) { return this._DefaultValueAccessor_61_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (61 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_61_4; }
    if (((token === import18.NgModel) && (61 === requestNodeIndex))) { return this._NgModel_61_5; }
    if (((token === import22.NgControl) && (61 === requestNodeIndex))) { return this._NgControl_61_6; }
    if (((token === import19.NgControlStatus) && (61 === requestNodeIndex))) { return this._NgControlStatus_61_7; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_4:any = this.context.$implicit.address1;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgModel_14_5.model = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgModel_14_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_14:any = this.context.$implicit.address2;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_25_5.model = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._NgModel_25_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_24:any = this.context.$implicit.city;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgModel_36_5.model = currVal_24;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_24,currVal_24);
      this._expr_24 = currVal_24;
    }
    if ((changes !== (null as any))) { this._NgModel_36_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_34:any = this.context.$implicit.stateId;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._NgModel_47_5.model = currVal_34;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_34,currVal_34);
      this._expr_34 = currVal_34;
    }
    if ((changes !== (null as any))) { this._NgModel_47_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_41:any = this.parent.context.states;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this._NgFor_49_6.ngForOf = currVal_41;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_41,currVal_41);
      this._expr_41 = currVal_41;
    }
    if ((changes !== (null as any))) { this._NgFor_49_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_49_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_45:any = this.context.$implicit.zipcode;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this._NgModel_61_5.model = currVal_45;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_45,currVal_45);
      this._expr_45 = currVal_45;
    }
    if ((changes !== (null as any))) { this._NgModel_61_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.addressType.displayName,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_5:any = this._NgControlStatus_14_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_14,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_14_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_14,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_14_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_14_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_14_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_14,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_14_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_14,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_15:any = this._NgControlStatus_25_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_25_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_25_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_25_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_25_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_25_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_25:any = this._NgControlStatus_36_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_36,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_36_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_36,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_36_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_36,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_36_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_36,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_36_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_36,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_36_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_36,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_35:any = this._NgControlStatus_47_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_47,'ng-untouched',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_47_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_47,'ng-touched',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_47_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_47,'ng-pristine',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_47_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_47,'ng-dirty',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_47_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_47,'ng-valid',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_47_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_47,'ng-invalid',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_46:any = this._NgControlStatus_61_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_61,'ng-untouched',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_61_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_61,'ng-touched',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_61_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_61,'ng-pristine',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_61_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_61,'ng-dirty',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._NgControlStatus_61_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_61,'ng-valid',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_61_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_61,'ng-invalid',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_53:any = this.context.$implicit.primary;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementProperty(this._el_73,'checked',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this.context.$implicit.primary;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementProperty(this._el_73,'disabled',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_56:any = (this.context.$implicit.primary || (this.parent.context.model.addresses.length === 1));
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementProperty(this._el_82,'disabled',currVal_56);
      this._expr_56 = currVal_56;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_14_5.ngOnDestroy();
    this._NgModel_25_5.ngOnDestroy();
    this._NgModel_36_5.ngOnDestroy();
    this._NgModel_47_5.ngOnDestroy();
    this._NgModel_61_5.ngOnDestroy();
  }
  private _handle_ngModelChange_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.address1 = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_14_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_14_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_14_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_14_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.address2 = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_25_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_36_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.city = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_36_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_36_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_36_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_36_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.stateId = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_change_47_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SelectControlValueAccessor_47_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_47_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SelectControlValueAccessor_47_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_61_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.zipcode = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_61_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_61_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_61_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_61_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_73_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.setPrimaryAddress(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_82_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.deleteAddress(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ResourceContactsComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceContactsComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceContactsComponent3 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import20.NgSelectOption;
  _NgSelectMultipleOption_0_4:import23.NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceContactsComponent3,renderType_ResourceContactsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'option',(null as any));
    this._NgSelectOption_0_3 = new import20.NgSelectOption(new import16.ElementRef(this._el_0),this.renderer,(<_View_ResourceContactsComponent2>this.parent)._SelectControlValueAccessor_47_3);
    this._NgSelectMultipleOption_0_4 = new import23.NgSelectMultipleOption(new import16.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3; }
    if (((token === import23.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit.id;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgSelectOption_0_3.ngValue = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.$implicit.id;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgSelectMultipleOption_0_4.ngValue = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
}
function viewFactory_ResourceContactsComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceContactsComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceContactsComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _NgClass_4_3:import14.NgClass;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_1:any;
  _map_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceContactsComponent4,renderType_ResourceContactsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','selectable');
    this._text_1 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'i',(null as any));
    this.renderer.setElementAttribute(this._el_4,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_4,'class','fa');
    this.renderer.setElementAttribute(this._el_4,'style','width: 20px; text-align: center');
    this._NgClass_4_3 = new import14.NgClass(this.parent.parentInjector.get(import13.IterableDiffers),this.parent.parentInjector.get(import15.KeyValueDiffers),new import16.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_4,'\n                                    ',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy3((p0:any,p1:any,p2:any):{[key: string]:any} => {
      return {
        'fa-mobile': p0,
        'fa-building-o': p1,
        'fa-home': p2
      }
      ;
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.NgClass) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._NgClass_4_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'fa';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_4_3.klass = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._map_0((this.context.$implicit.name == 'Mobile'),(this.context.$implicit.name == 'Work'),(this.context.$implicit.name == 'Home'));
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_4_3.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_4_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = import4.interpolate(1,'\n                                    New ',this.context.$implicit.name,' Phone\n                                ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_6,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.addPhoneNumber(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ResourceContactsComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceContactsComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_ResourceContactsComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _DefaultValueAccessor_11_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_11_4:any[];
  _NgModel_11_5:import18.NgModel;
  _NgControl_11_6:any;
  _NgControlStatus_11_7:import19.NgControlStatus;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _DefaultValueAccessor_16_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_16_4:any[];
  _NgModel_16_5:import18.NgModel;
  _NgControl_16_6:any;
  _NgControlStatus_16_7:import19.NgControlStatus;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_25:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ResourceContactsComponent5,renderType_ResourceContactsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this.renderer.setElementAttribute(this._el_0,'style','margin-top: 20px');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-sm-10 form-horizontal');
    this._text_3 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','form-group');
    this._text_5 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'label',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-sm-3 control-label');
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-sm-3');
    this._text_10 = this.renderer.createText(this._el_9,'\n                            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'input',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','form-control');
    this.renderer.setElementAttribute(this._el_11,'type','text');
    this._DefaultValueAccessor_11_3 = new import17.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_11));
    this._NG_VALUE_ACCESSOR_11_4 = [this._DefaultValueAccessor_11_3];
    this._NgModel_11_5 = new import18.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_11_4);
    this._NgControl_11_6 = this._NgModel_11_5;
    this._NgControlStatus_11_7 = new import19.NgControlStatus(this._NgControl_11_6);
    this._text_12 = this.renderer.createText(this._el_9,'\n                        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','col-sm-6');
    this._text_15 = this.renderer.createText(this._el_14,'\n                            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'input',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-control');
    this.renderer.setElementAttribute(this._el_16,'type','text');
    this._DefaultValueAccessor_16_3 = new import17.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_16));
    this._NG_VALUE_ACCESSOR_16_4 = [this._DefaultValueAccessor_16_3];
    this._NgModel_16_5 = new import18.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_16_4);
    this._NgControl_16_6 = this._NgModel_16_5;
    this._NgControlStatus_16_7 = new import19.NgControlStatus(this._NgControl_16_6);
    this._text_17 = this.renderer.createText(this._el_14,'\n                        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','form-group');
    this._text_21 = this.renderer.createText(this._el_20,'\n                        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','col-sm-offset-3 col-sm-9');
    this._text_23 = this.renderer.createText(this._el_22,'\n                            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','checkbox');
    this._text_25 = this.renderer.createText(this._el_24,'\n                                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'label',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                                    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'input',(null as any));
    this.renderer.setElementAttribute(this._el_28,'type','checkbox');
    this._text_29 = this.renderer.createText(this._el_26,' Primary\n                                ',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n                            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_22,'\n                        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','col-sm-2');
    this._text_36 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'button',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','btn btn-danger');
    this.renderer.setElementAttribute(this._el_37,'style','margin-left: 5px');
    this.renderer.setElementAttribute(this._el_37,'title','Delete...');
    this._el_38 = this.renderer.createElement(this._el_37,'i',(null as any));
    this.renderer.setElementAttribute(this._el_38,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_38,'class','fa fa-trash-o');
    this._text_39 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'ngModelChange',this.eventHandler(this._handle_ngModelChange_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'input',this.eventHandler(this._handle_input_11_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'blur',this.eventHandler(this._handle_blur_11_2.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_11_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_11_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_16,'ngModelChange',this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_16,'input',this.eventHandler(this._handle_input_16_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_16,'blur',this.eventHandler(this._handle_blur_16_2.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_16_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._el_38,
      this._text_39,
      this._text_40
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.DefaultValueAccessor) && (11 === requestNodeIndex))) { return this._DefaultValueAccessor_11_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_4; }
    if (((token === import18.NgModel) && (11 === requestNodeIndex))) { return this._NgModel_11_5; }
    if (((token === import22.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_6; }
    if (((token === import19.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_7; }
    if (((token === import17.DefaultValueAccessor) && (16 === requestNodeIndex))) { return this._DefaultValueAccessor_16_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (16 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_16_4; }
    if (((token === import18.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_5; }
    if (((token === import22.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_6; }
    if (((token === import19.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_7; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_4:any = this.context.$implicit.areaCode;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgModel_11_5.model = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgModel_11_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_14:any = this.context.$implicit.number;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_16_5.model = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._NgModel_16_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.phoneNumberType.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_5:any = this._NgControlStatus_11_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_11_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_11_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_11_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_11_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_11_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_15:any = this._NgControlStatus_16_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_16_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_16_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_16_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_16_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_16_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_22:any = this.context.$implicit.primary;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementProperty(this._el_28,'checked',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this.context.$implicit.primary;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementProperty(this._el_28,'disabled',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_25:any = (this.context.$implicit.primary || (this.parent.context.model.phoneNumbers.length === 1));
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementProperty(this._el_37,'disabled',currVal_25);
      this._expr_25 = currVal_25;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_11_5.ngOnDestroy();
    this._NgModel_16_5.ngOnDestroy();
  }
  private _handle_ngModelChange_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.areaCode = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_11_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_11_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_11_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.number = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_16_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_16_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_16_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_16_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.setPrimaryPhoneNumber(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.deletePhoneNumber(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ResourceContactsComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ResourceContactsComponent5(viewUtils,parentInjector,declarationEl);
}