/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/http/src/http_module';
import * as import3 from '@angular/http/src/backends/browser_xhr';
import * as import4 from '@angular/http/src/base_response_options';
import * as import5 from '@angular/http/src/backends/xhr_backend';
import * as import6 from '@angular/http/src/base_request_options';
import * as import7 from 'breeze-bridge-angular2/index';
import * as import8 from '@angular/common/src/common_module';
import * as import9 from '@angular/core/src/application_module';
import * as import10 from '@angular/platform-browser/src/browser';
import * as import11 from '@angular/forms/src/directives';
import * as import12 from '@angular/forms/src/form_providers';
import * as import13 from '@angular/router/src/router_module';
import * as import14 from '../../app/shared/shared.module';
import * as import15 from '../../app/core/core.module';
import * as import16 from '../../app/resourcemgt/resource-mgt.module';
import * as import17 from '@angular/common/src/localization';
import * as import18 from '../../app/core/services/dialog.service';
import * as import19 from '../../app/core/services/error-handler';
import * as import20 from '@angular/core/src/application_init';
import * as import21 from '@angular/core/src/testability/testability';
import * as import22 from '@angular/core/src/application_ref';
import * as import23 from '@angular/core/src/linker/compiler';
import * as import24 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import25 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import26 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import27 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import28 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import29 from '@angular/core/src/linker/view_utils';
import * as import30 from '@angular/platform-browser/src/browser/title';
import * as import31 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import32 from '../../app/core/services/entity-manager-provider';
import * as import33 from '../../app/shared/services/unit-of-work';
import * as import34 from '../../app/core/services/guards';
import * as import35 from '../../app/core/services/auth.service';
import * as import36 from '@angular/router/src/url_tree';
import * as import37 from '@angular/router/src/router_outlet_map';
import * as import38 from '@angular/common/src/location/location';
import * as import39 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import40 from '../../app/core/services/busy.service';
import * as import41 from '../../app/resourcemgt/resource-mgt-unit-of-work';
import * as import42 from '@angular/core/src/di/injector';
import * as import43 from './resourcemgt/resource-mgt.component.ngfactory';
import * as import44 from './resourcemgt/resource-detail.component.ngfactory';
import * as import45 from './login.component.ngfactory';
import * as import46 from './home.component.ngfactory';
import * as import47 from './app.component.ngfactory';
import * as import48 from '@angular/core/src/application_tokens';
import * as import49 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import50 from '@angular/platform-browser/src/dom/events/key_events';
import * as import51 from '@angular/core/src/zone/ng_zone';
import * as import52 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import53 from '@angular/common/src/location/platform_location';
import * as import54 from '@angular/common/src/location/location_strategy';
import * as import55 from '../../app/resourcemgt/resource-mgt.component';
import * as import56 from '../../app/resourcemgt/resource-detail.component';
import * as import57 from '../../app/login.component';
import * as import58 from '../../app/home.component';
import * as import59 from '@angular/router/src/router';
import * as import60 from '../../app/core/services/custom-exception-handler';
import * as import61 from '@angular/core/src/console';
import * as import62 from '@angular/http/src/interfaces';
import * as import63 from '@angular/http/src/http';
import * as import64 from '@angular/core/src/i18n/tokens';
import * as import65 from '@angular/core/src/error_handler';
import * as import66 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import67 from '@angular/platform-browser/src/dom/animation_driver';
import * as import68 from '@angular/core/src/render/api';
import * as import69 from '@angular/core/src/security';
import * as import70 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import71 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import72 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import73 from '@angular/router/src/router_config_loader';
import * as import74 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _HttpModule_0:import2.HttpModule;
  _BrowserXhr_1:import3.BrowserXhr;
  _ResponseOptions_2:import4.BaseResponseOptions;
  _XSRFStrategy_3:any;
  _XHRBackend_4:import5.XHRBackend;
  _RequestOptions_5:import6.BaseRequestOptions;
  _Http_6:any;
  _BreezeBridgeAngular2Module_7:import7.BreezeBridgeAngular2Module;
  _CommonModule_8:import8.CommonModule;
  _ApplicationModule_9:import9.ApplicationModule;
  _BrowserModule_10:import10.BrowserModule;
  _InternalFormsSharedModule_11:import11.InternalFormsSharedModule;
  _FormsModule_12:import12.FormsModule;
  _ROUTER_FORROOT_GUARD_13:any;
  _RouterModule_14:import13.RouterModule;
  _SharedModule_15:import14.SharedModule;
  _CoreModule_16:import15.CoreModule;
  _ResourceMgtModule_17:import16.ResourceMgtModule;
  _AppModule_18:import1.AppModule;
  __LOCALE_ID_19:any;
  __NgLocalization_20:import17.NgLocaleLocalization;
  _DialogService_21:import18.DialogService;
  _ErrorHandler_22:import19.ErrorHandler;
  _ErrorHandler_23:any;
  _ApplicationInitStatus_24:import20.ApplicationInitStatus;
  _Testability_25:import21.Testability;
  _ApplicationRef__26:import22.ApplicationRef_;
  __ApplicationRef_27:any;
  __Compiler_28:import23.Compiler;
  __APP_ID_29:any;
  __DOCUMENT_30:any;
  __HAMMER_GESTURE_CONFIG_31:import24.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_32:any[];
  __EventManager_33:import25.EventManager;
  __DomSharedStylesHost_34:import26.DomSharedStylesHost;
  __AnimationDriver_35:any;
  __DomRootRenderer_36:import27.DomRootRenderer_;
  __RootRenderer_37:any;
  __DomSanitizer_38:import28.DomSanitizerImpl;
  __Sanitizer_39:any;
  __ViewUtils_40:import29.ViewUtils;
  __IterableDiffers_41:any;
  __KeyValueDiffers_42:any;
  __SharedStylesHost_43:any;
  __Title_44:import30.Title;
  __RadioControlRegistry_45:import31.RadioControlRegistry;
  __EntityManagerProvider_46:import32.EntityManagerProvider;
  __UnitOfWork_47:import33.UnitOfWork;
  __CanDeactivateGuard_48:import34.CanDeactivateGuard;
  __AuthService_49:import35.AuthService;
  __UrlSerializer_50:import36.DefaultUrlSerializer;
  __RouterOutletMap_51:import37.RouterOutletMap;
  __ROUTER_CONFIGURATION_52:any;
  __LocationStrategy_53:any;
  __Location_54:import38.Location;
  __NgModuleFactoryLoader_55:import39.SystemJsNgModuleLoader;
  __ROUTES_56:any[];
  __Router_57:any;
  __PrepareGuard_58:import34.PrepareGuard;
  __BusyService_59:import40.BusyService;
  __ResourceMgtUnitOfWork_60:import41.ResourceMgtUnitOfWork;
  __ActivatedRoute_61:any;
  __APP_BOOTSTRAP_LISTENER_62:any[];
  constructor(parent:import42.Injector) {
    super(parent,[
      import43.ResourceMgtComponentNgFactory,
      import43.ResourceMgtComponentNgFactory,
      import44.ResourceDetailComponentNgFactory,
      import45.LoginComponentNgFactory,
      import46.HomeComponentNgFactory,
      import47.AppComponentNgFactory
    ]
    ,[import47.AppComponentNgFactory]);
  }
  get _LOCALE_ID_19():any {
    if ((this.__LOCALE_ID_19 == (null as any))) { (this.__LOCALE_ID_19 = 'en-US'); }
    return this.__LOCALE_ID_19;
  }
  get _NgLocalization_20():import17.NgLocaleLocalization {
    if ((this.__NgLocalization_20 == (null as any))) { (this.__NgLocalization_20 = new import17.NgLocaleLocalization(this._LOCALE_ID_19)); }
    return this.__NgLocalization_20;
  }
  get _ApplicationRef_27():any {
    if ((this.__ApplicationRef_27 == (null as any))) { (this.__ApplicationRef_27 = this._ApplicationRef__26); }
    return this.__ApplicationRef_27;
  }
  get _Compiler_28():import23.Compiler {
    if ((this.__Compiler_28 == (null as any))) { (this.__Compiler_28 = new import23.Compiler()); }
    return this.__Compiler_28;
  }
  get _APP_ID_29():any {
    if ((this.__APP_ID_29 == (null as any))) { (this.__APP_ID_29 = import48._appIdRandomProviderFactory()); }
    return this.__APP_ID_29;
  }
  get _DOCUMENT_30():any {
    if ((this.__DOCUMENT_30 == (null as any))) { (this.__DOCUMENT_30 = import10._document()); }
    return this.__DOCUMENT_30;
  }
  get _HAMMER_GESTURE_CONFIG_31():import24.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_31 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_31 = new import24.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_31;
  }
  get _EVENT_MANAGER_PLUGINS_32():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_32 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_32 = [
      new import49.DomEventsPlugin(),
      new import50.KeyEventsPlugin(),
      new import24.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_31)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_32;
  }
  get _EventManager_33():import25.EventManager {
    if ((this.__EventManager_33 == (null as any))) { (this.__EventManager_33 = new import25.EventManager(this._EVENT_MANAGER_PLUGINS_32,this.parent.get(import51.NgZone))); }
    return this.__EventManager_33;
  }
  get _DomSharedStylesHost_34():import26.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_34 == (null as any))) { (this.__DomSharedStylesHost_34 = new import26.DomSharedStylesHost(this._DOCUMENT_30)); }
    return this.__DomSharedStylesHost_34;
  }
  get _AnimationDriver_35():any {
    if ((this.__AnimationDriver_35 == (null as any))) { (this.__AnimationDriver_35 = import10._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_35;
  }
  get _DomRootRenderer_36():import27.DomRootRenderer_ {
    if ((this.__DomRootRenderer_36 == (null as any))) { (this.__DomRootRenderer_36 = new import27.DomRootRenderer_(this._DOCUMENT_30,this._EventManager_33,this._DomSharedStylesHost_34,this._AnimationDriver_35)); }
    return this.__DomRootRenderer_36;
  }
  get _RootRenderer_37():any {
    if ((this.__RootRenderer_37 == (null as any))) { (this.__RootRenderer_37 = import52._createConditionalRootRenderer(this._DomRootRenderer_36,this.parent.get(import52.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_37;
  }
  get _DomSanitizer_38():import28.DomSanitizerImpl {
    if ((this.__DomSanitizer_38 == (null as any))) { (this.__DomSanitizer_38 = new import28.DomSanitizerImpl()); }
    return this.__DomSanitizer_38;
  }
  get _Sanitizer_39():any {
    if ((this.__Sanitizer_39 == (null as any))) { (this.__Sanitizer_39 = this._DomSanitizer_38); }
    return this.__Sanitizer_39;
  }
  get _ViewUtils_40():import29.ViewUtils {
    if ((this.__ViewUtils_40 == (null as any))) { (this.__ViewUtils_40 = new import29.ViewUtils(this._RootRenderer_37,this._APP_ID_29,this._Sanitizer_39)); }
    return this.__ViewUtils_40;
  }
  get _IterableDiffers_41():any {
    if ((this.__IterableDiffers_41 == (null as any))) { (this.__IterableDiffers_41 = import9._iterableDiffersFactory()); }
    return this.__IterableDiffers_41;
  }
  get _KeyValueDiffers_42():any {
    if ((this.__KeyValueDiffers_42 == (null as any))) { (this.__KeyValueDiffers_42 = import9._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_42;
  }
  get _SharedStylesHost_43():any {
    if ((this.__SharedStylesHost_43 == (null as any))) { (this.__SharedStylesHost_43 = this._DomSharedStylesHost_34); }
    return this.__SharedStylesHost_43;
  }
  get _Title_44():import30.Title {
    if ((this.__Title_44 == (null as any))) { (this.__Title_44 = new import30.Title()); }
    return this.__Title_44;
  }
  get _RadioControlRegistry_45():import31.RadioControlRegistry {
    if ((this.__RadioControlRegistry_45 == (null as any))) { (this.__RadioControlRegistry_45 = new import31.RadioControlRegistry()); }
    return this.__RadioControlRegistry_45;
  }
  get _EntityManagerProvider_46():import32.EntityManagerProvider {
    if ((this.__EntityManagerProvider_46 == (null as any))) { (this.__EntityManagerProvider_46 = new import32.EntityManagerProvider()); }
    return this.__EntityManagerProvider_46;
  }
  get _UnitOfWork_47():import33.UnitOfWork {
    if ((this.__UnitOfWork_47 == (null as any))) { (this.__UnitOfWork_47 = new import33.UnitOfWork(this._EntityManagerProvider_46)); }
    return this.__UnitOfWork_47;
  }
  get _CanDeactivateGuard_48():import34.CanDeactivateGuard {
    if ((this.__CanDeactivateGuard_48 == (null as any))) { (this.__CanDeactivateGuard_48 = new import34.CanDeactivateGuard()); }
    return this.__CanDeactivateGuard_48;
  }
  get _AuthService_49():import35.AuthService {
    if ((this.__AuthService_49 == (null as any))) { (this.__AuthService_49 = new import35.AuthService(this._Http_6)); }
    return this.__AuthService_49;
  }
  get _UrlSerializer_50():import36.DefaultUrlSerializer {
    if ((this.__UrlSerializer_50 == (null as any))) { (this.__UrlSerializer_50 = new import36.DefaultUrlSerializer()); }
    return this.__UrlSerializer_50;
  }
  get _RouterOutletMap_51():import37.RouterOutletMap {
    if ((this.__RouterOutletMap_51 == (null as any))) { (this.__RouterOutletMap_51 = new import37.RouterOutletMap()); }
    return this.__RouterOutletMap_51;
  }
  get _ROUTER_CONFIGURATION_52():any {
    if ((this.__ROUTER_CONFIGURATION_52 == (null as any))) { (this.__ROUTER_CONFIGURATION_52 = {
      enableTracing: true,
      useHash: true
    }
    ); }
    return this.__ROUTER_CONFIGURATION_52;
  }
  get _LocationStrategy_53():any {
    if ((this.__LocationStrategy_53 == (null as any))) { (this.__LocationStrategy_53 = import13.provideLocationStrategy(this.parent.get(import53.PlatformLocation),this.parent.get(import54.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_52)); }
    return this.__LocationStrategy_53;
  }
  get _Location_54():import38.Location {
    if ((this.__Location_54 == (null as any))) { (this.__Location_54 = new import38.Location(this._LocationStrategy_53)); }
    return this.__Location_54;
  }
  get _NgModuleFactoryLoader_55():import39.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_55 == (null as any))) { (this.__NgModuleFactoryLoader_55 = new import39.SystemJsNgModuleLoader(this._Compiler_28,this.parent.get(import39.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_55;
  }
  get _ROUTES_56():any[] {
    if ((this.__ROUTES_56 == (null as any))) { (this.__ROUTES_56 = [
      [
        {
          path: 'resourcemgt',
          component: import55.ResourceMgtComponent,
          canActivate: [import34.PrepareGuard]
        }
        ,
        {
          path: 'resourcemgt',
          component: import55.ResourceMgtComponent,
          canActivate: [import34.PrepareGuard],
            children: [{
              path: ':id',
              component: import56.ResourceDetailComponent,
              canDeactivate: [import34.CanDeactivateGuard]
            }
          ]
        }

      ]
      ,
      [
        {
          path: '',
          redirectTo: 'home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'login',
          component: import57.LoginComponent
        }
        ,
        {
          path: 'home',
          component: import58.HomeComponent,
          canActivate: [import34.PrepareGuard]
        }

      ]

    ]
    ); }
    return this.__ROUTES_56;
  }
  get _Router_57():any {
    if ((this.__Router_57 == (null as any))) { (this.__Router_57 = import13.setupRouter(this._ApplicationRef_27,this._UrlSerializer_50,this._RouterOutletMap_51,this._Location_54,this,this._NgModuleFactoryLoader_55,this._Compiler_28,this._ROUTES_56,this._ROUTER_CONFIGURATION_52)); }
    return this.__Router_57;
  }
  get _PrepareGuard_58():import34.PrepareGuard {
    if ((this.__PrepareGuard_58 == (null as any))) { (this.__PrepareGuard_58 = new import34.PrepareGuard(this._EntityManagerProvider_46,this._AuthService_49,this._Router_57)); }
    return this.__PrepareGuard_58;
  }
  get _BusyService_59():import40.BusyService {
    if ((this.__BusyService_59 == (null as any))) { (this.__BusyService_59 = new import40.BusyService()); }
    return this.__BusyService_59;
  }
  get _ResourceMgtUnitOfWork_60():import41.ResourceMgtUnitOfWork {
    if ((this.__ResourceMgtUnitOfWork_60 == (null as any))) { (this.__ResourceMgtUnitOfWork_60 = new import41.ResourceMgtUnitOfWork(this._EntityManagerProvider_46)); }
    return this.__ResourceMgtUnitOfWork_60;
  }
  get _ActivatedRoute_61():any {
    if ((this.__ActivatedRoute_61 == (null as any))) { (this.__ActivatedRoute_61 = import13.rootRoute(this._Router_57)); }
    return this.__ActivatedRoute_61;
  }
  get _APP_BOOTSTRAP_LISTENER_62():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_62 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_62 = [import13.initialRouterNavigation(this._Router_57,this._ROUTER_CONFIGURATION_52)]); }
    return this.__APP_BOOTSTRAP_LISTENER_62;
  }
  createInternal():import1.AppModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._BrowserXhr_1 = new import3.BrowserXhr();
    this._ResponseOptions_2 = new import4.BaseResponseOptions();
    this._XSRFStrategy_3 = import2._createDefaultCookieXSRFStrategy();
    this._XHRBackend_4 = new import5.XHRBackend(this._BrowserXhr_1,this._ResponseOptions_2,this._XSRFStrategy_3);
    this._RequestOptions_5 = new import6.BaseRequestOptions();
    this._Http_6 = import2.httpFactory(this._XHRBackend_4,this._RequestOptions_5);
    this._BreezeBridgeAngular2Module_7 = new import7.BreezeBridgeAngular2Module(this._Http_6);
    this._CommonModule_8 = new import8.CommonModule();
    this._ApplicationModule_9 = new import9.ApplicationModule();
    this._BrowserModule_10 = new import10.BrowserModule(this.parent.get(import10.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_11 = new import11.InternalFormsSharedModule();
    this._FormsModule_12 = new import12.FormsModule();
    this._ROUTER_FORROOT_GUARD_13 = import13.provideForRootGuard(this.parent.get(import59.Router,(null as any)));
    this._RouterModule_14 = new import13.RouterModule(this._ROUTER_FORROOT_GUARD_13);
    this._SharedModule_15 = new import14.SharedModule();
    this._CoreModule_16 = new import15.CoreModule();
    this._ResourceMgtModule_17 = new import16.ResourceMgtModule();
    this._AppModule_18 = new import1.AppModule();
    this._DialogService_21 = new import18.DialogService();
    this._ErrorHandler_22 = new import19.ErrorHandler(this._DialogService_21);
    this._ErrorHandler_23 = import60.CustomExceptionHandlerFactory(this._ErrorHandler_22);
    this._ApplicationInitStatus_24 = new import20.ApplicationInitStatus(this.parent.get(import20.APP_INITIALIZER,(null as any)));
    this._Testability_25 = new import21.Testability(this.parent.get(import51.NgZone));
    this._ApplicationRef__26 = new import22.ApplicationRef_(this.parent.get(import51.NgZone),this.parent.get(import61.Console),this,this._ErrorHandler_23,this,this._ApplicationInitStatus_24,this.parent.get(import21.TestabilityRegistry,(null as any)),this._Testability_25);
    return this._AppModule_18;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.BrowserXhr)) { return this._BrowserXhr_1; }
    if ((token === import4.ResponseOptions)) { return this._ResponseOptions_2; }
    if ((token === import62.XSRFStrategy)) { return this._XSRFStrategy_3; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_4; }
    if ((token === import6.RequestOptions)) { return this._RequestOptions_5; }
    if ((token === import63.Http)) { return this._Http_6; }
    if ((token === import7.BreezeBridgeAngular2Module)) { return this._BreezeBridgeAngular2Module_7; }
    if ((token === import8.CommonModule)) { return this._CommonModule_8; }
    if ((token === import9.ApplicationModule)) { return this._ApplicationModule_9; }
    if ((token === import10.BrowserModule)) { return this._BrowserModule_10; }
    if ((token === import11.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_11; }
    if ((token === import12.FormsModule)) { return this._FormsModule_12; }
    if ((token === import13.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_13; }
    if ((token === import13.RouterModule)) { return this._RouterModule_14; }
    if ((token === import14.SharedModule)) { return this._SharedModule_15; }
    if ((token === import15.CoreModule)) { return this._CoreModule_16; }
    if ((token === import16.ResourceMgtModule)) { return this._ResourceMgtModule_17; }
    if ((token === import1.AppModule)) { return this._AppModule_18; }
    if ((token === import64.LOCALE_ID)) { return this._LOCALE_ID_19; }
    if ((token === import17.NgLocalization)) { return this._NgLocalization_20; }
    if ((token === import18.DialogService)) { return this._DialogService_21; }
    if ((token === import19.ErrorHandler)) { return this._ErrorHandler_22; }
    if ((token === import65.ErrorHandler)) { return this._ErrorHandler_23; }
    if ((token === import20.ApplicationInitStatus)) { return this._ApplicationInitStatus_24; }
    if ((token === import21.Testability)) { return this._Testability_25; }
    if ((token === import22.ApplicationRef_)) { return this._ApplicationRef__26; }
    if ((token === import22.ApplicationRef)) { return this._ApplicationRef_27; }
    if ((token === import23.Compiler)) { return this._Compiler_28; }
    if ((token === import48.APP_ID)) { return this._APP_ID_29; }
    if ((token === import66.DOCUMENT)) { return this._DOCUMENT_30; }
    if ((token === import24.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_31; }
    if ((token === import25.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_32; }
    if ((token === import25.EventManager)) { return this._EventManager_33; }
    if ((token === import26.DomSharedStylesHost)) { return this._DomSharedStylesHost_34; }
    if ((token === import67.AnimationDriver)) { return this._AnimationDriver_35; }
    if ((token === import27.DomRootRenderer)) { return this._DomRootRenderer_36; }
    if ((token === import68.RootRenderer)) { return this._RootRenderer_37; }
    if ((token === import28.DomSanitizer)) { return this._DomSanitizer_38; }
    if ((token === import69.Sanitizer)) { return this._Sanitizer_39; }
    if ((token === import29.ViewUtils)) { return this._ViewUtils_40; }
    if ((token === import70.IterableDiffers)) { return this._IterableDiffers_41; }
    if ((token === import71.KeyValueDiffers)) { return this._KeyValueDiffers_42; }
    if ((token === import26.SharedStylesHost)) { return this._SharedStylesHost_43; }
    if ((token === import30.Title)) { return this._Title_44; }
    if ((token === import31.RadioControlRegistry)) { return this._RadioControlRegistry_45; }
    if ((token === import32.EntityManagerProvider)) { return this._EntityManagerProvider_46; }
    if ((token === import33.UnitOfWork)) { return this._UnitOfWork_47; }
    if ((token === import34.CanDeactivateGuard)) { return this._CanDeactivateGuard_48; }
    if ((token === import35.AuthService)) { return this._AuthService_49; }
    if ((token === import36.UrlSerializer)) { return this._UrlSerializer_50; }
    if ((token === import37.RouterOutletMap)) { return this._RouterOutletMap_51; }
    if ((token === import13.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_52; }
    if ((token === import54.LocationStrategy)) { return this._LocationStrategy_53; }
    if ((token === import38.Location)) { return this._Location_54; }
    if ((token === import72.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_55; }
    if ((token === import73.ROUTES)) { return this._ROUTES_56; }
    if ((token === import59.Router)) { return this._Router_57; }
    if ((token === import34.PrepareGuard)) { return this._PrepareGuard_58; }
    if ((token === import40.BusyService)) { return this._BusyService_59; }
    if ((token === import41.ResourceMgtUnitOfWork)) { return this._ResourceMgtUnitOfWork_60; }
    if ((token === import74.ActivatedRoute)) { return this._ActivatedRoute_61; }
    if ((token === import48.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_62; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__26.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);