/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../app/login.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../app/core/services/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../app/core/services/dialog.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../app/shared/directives/scroll-to-top.directive';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/ng_model';
import * as import16 from '@angular/forms/src/directives/ng_control_status';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/forms/src/directives/control_value_accessor';
import * as import19 from '@angular/forms/src/directives/ng_control';
var renderType_LoginComponent_Host:import0.RenderComponentType = (null as any);
class _View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LoginComponent_0_4:import3.LoginComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginComponent_Host0,renderType_LoginComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginComponent_0_4 = new import3.LoginComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.DialogService));
    this._appEl_0.initComponent(this._LoginComponent_0_4,[],compView_0);
    compView_0.create(this._LoginComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LoginComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoginComponent_Host === (null as any))) { (renderType_LoginComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_LoginComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginComponentNgFactory:import12.ComponentFactory<import3.LoginComponent> = new import12.ComponentFactory<import3.LoginComponent>('ng-component',viewFactory_LoginComponent_Host0,import3.LoginComponent);
const styles_LoginComponent:any[] = [];
var renderType_LoginComponent:import0.RenderComponentType = (null as any);
class _View_LoginComponent0 extends import1.AppView<import3.LoginComponent> {
  _el_0:any;
  _ScrollToTopDirective_0_3:import13.ScrollToTopDirective;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _DefaultValueAccessor_14_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_14_4:any[];
  _NgModel_14_5:import15.NgModel;
  _NgControl_14_6:any;
  _NgControlStatus_14_7:import16.NgControlStatus;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_25_4:any[];
  _NgModel_25_5:import15.NgModel;
  _NgControl_25_6:any;
  _NgControlStatus_25_7:import16.NgControlStatus;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginComponent0,renderType_LoginComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'scrollToTop','');
    this._ScrollToTopDirective_0_3 = new import13.ScrollToTopDirective();
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h3',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Enter your login credentials:',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','form-horizontal');
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','form-group');
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'label',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-sm-1 control-label');
    this.renderer.setElementAttribute(this._el_9,'for','username');
    this._text_10 = this.renderer.createText(this._el_9,'Username',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','col-sm-5');
    this._text_13 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'input',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','form-control');
    this.renderer.setElementAttribute(this._el_14,'id','username');
    this.renderer.setElementAttribute(this._el_14,'placeholder','Username');
    this.renderer.setElementAttribute(this._el_14,'type','text');
    this._DefaultValueAccessor_14_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_14));
    this._NG_VALUE_ACCESSOR_14_4 = [this._DefaultValueAccessor_14_3];
    this._NgModel_14_5 = new import15.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_14_4);
    this._NgControl_14_6 = this._NgModel_14_5;
    this._NgControlStatus_14_7 = new import16.NgControlStatus(this._NgControl_14_6);
    this._text_15 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','form-group');
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'label',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','col-sm-1 control-label');
    this.renderer.setElementAttribute(this._el_20,'for','password');
    this._text_21 = this.renderer.createText(this._el_20,'Password',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','col-sm-5');
    this._text_24 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','form-control');
    this.renderer.setElementAttribute(this._el_25,'id','password');
    this.renderer.setElementAttribute(this._el_25,'placeholder','Password');
    this.renderer.setElementAttribute(this._el_25,'type','password');
    this._DefaultValueAccessor_25_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_25));
    this._NG_VALUE_ACCESSOR_25_4 = [this._DefaultValueAccessor_25_3];
    this._NgModel_25_5 = new import15.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_25_4);
    this._NgControl_25_6 = this._NgModel_25_5;
    this._NgControlStatus_25_7 = new import16.NgControlStatus(this._NgControl_25_6);
    this._text_26 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_28 = this.renderer.createText(this._el_5,'\n\n        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-group');
    this._text_30 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'div',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','col-sm-offset-1 col-sm-10');
    this._text_32 = this.renderer.createText(this._el_31,'\n                ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'button',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_33,'type','button');
    this._text_34 = this.renderer.createText(this._el_33,'Sign in',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._text_36 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._text_37 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_39 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_14,'ngModelChange',this.eventHandler(this._handle_ngModelChange_14_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_14,'input',this.eventHandler(this._handle_input_14_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_14,'blur',this.eventHandler(this._handle_blur_14_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_14_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_14_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_25,'ngModelChange',this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_25,'input',this.eventHandler(this._handle_input_25_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_25,'blur',this.eventHandler(this._handle_blur_25_2.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_25_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_33,'click',this.eventHandler(this._handle_click_33_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (14 === requestNodeIndex))) { return this._DefaultValueAccessor_14_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (14 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_14_4; }
    if (((token === import15.NgModel) && (14 === requestNodeIndex))) { return this._NgModel_14_5; }
    if (((token === import19.NgControl) && (14 === requestNodeIndex))) { return this._NgControl_14_6; }
    if (((token === import16.NgControlStatus) && (14 === requestNodeIndex))) { return this._NgControlStatus_14_7; }
    if (((token === import14.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_4; }
    if (((token === import15.NgModel) && (25 === requestNodeIndex))) { return this._NgModel_25_5; }
    if (((token === import19.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_6; }
    if (((token === import16.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_7; }
    if (((token === import13.ScrollToTopDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ScrollToTopDirective_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScrollToTopDirective_0_3.ngOnInit(); }
    changes = (null as any);
    const currVal_3:any = this.context.username;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgModel_14_5.model = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgModel_14_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_13:any = this.context.password;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgModel_25_5.model = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgModel_25_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatus_14_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_14,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_14_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_14,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_14_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_14,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_14_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_14_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_14_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_14,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_14:any = this._NgControlStatus_25_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_25_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_25_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_25_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_25_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_25_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_21:boolean = !this.context.isValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementProperty(this._el_33,'disabled',currVal_21);
      this._expr_21 = currVal_21;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_14_5.ngOnDestroy();
    this._NgModel_25_5.ngOnDestroy();
  }
  private _handle_ngModelChange_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.username = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_14_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_14_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_14_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_14_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_25_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loginUser()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LoginComponent> {
  if ((renderType_LoginComponent === (null as any))) { (renderType_LoginComponent = viewUtils.createRenderComponentType('C:/Workspace/Frameworks/temphire.angular2/TempHire/app/login.html',0,import11.ViewEncapsulation.None,styles_LoginComponent,{})); }
  return new _View_LoginComponent0(viewUtils,parentInjector,declarationEl);
}