/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../app/nav-bar.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../app/core/services/busy.service';
import * as import9 from '../../app/core/services/auth.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/router/src/directives/router_link';
import * as import13 from '@angular/common/src/directives/ng_for';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/router/src/router';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/common/src/location/location_strategy';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/core/src/security';
import * as import21 from '@angular/router/src/directives/router_link_active';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '@angular/core/src/linker/element_ref';
var renderType_NavBarComponent_Host:import0.RenderComponentType = (null as any);
class _View_NavBarComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _NavBarComponent_0_4:import3.NavBarComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NavBarComponent_Host0,renderType_NavBarComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('nav-bar',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NavBarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NavBarComponent_0_4 = new import3.NavBarComponent(this.parentInjector.get(import8.BusyService),this.parentInjector.get(import9.AuthService));
    this._appEl_0.initComponent(this._NavBarComponent_0_4,[],compView_0);
    compView_0.create(this._NavBarComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.NavBarComponent) && (0 === requestNodeIndex))) { return this._NavBarComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_NavBarComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_NavBarComponent_Host === (null as any))) { (renderType_NavBarComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_NavBarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NavBarComponentNgFactory:import11.ComponentFactory<import3.NavBarComponent> = new import11.ComponentFactory<import3.NavBarComponent>('nav-bar',viewFactory_NavBarComponent_Host0,import3.NavBarComponent);
const styles_NavBarComponent:any[] = [];
var renderType_NavBarComponent:import0.RenderComponentType = (null as any);
class _View_NavBarComponent0 extends import1.AppView<import3.NavBarComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import12.RouterLinkWithHref;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _NgFor_26_6:import13.NgFor;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import14.NgIf;
  _text_32:any;
  _el_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NavBarComponent0,renderType_NavBarComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','navbar navbar-inverse navbar-fixed-top');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','navbar-header');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'aria-controls','navbar');
    this.renderer.setElementAttribute(this._el_6,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_6,'class','navbar-toggle collapsed');
    this.renderer.setElementAttribute(this._el_6,'data-target','#navbar');
    this.renderer.setElementAttribute(this._el_6,'data-toggle','collapse');
    this.renderer.setElementAttribute(this._el_6,'type','button');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'span',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','sr-only');
    this._text_9 = this.renderer.createText(this._el_8,'Toggle navigation',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'span',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','icon-bar');
    this._text_12 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_6,'span',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','icon-bar');
    this._text_14 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_6,'span',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','icon-bar');
    this._text_16 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_4,'a',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','navbar-brand');
    this.renderer.setElementAttribute(this._el_18,'routerLink','/');
    this._RouterLinkWithHref_18_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._text_19 = this.renderer.createText(this._el_18,'TempHire Angular 2',(null as any));
    this._text_20 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','navbar-collapse collapse');
    this.renderer.setElementAttribute(this._el_22,'id','navbar');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','nav navbar-nav');
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_26 = new import2.AppElement(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import18.TemplateRef_(this._appEl_26,viewFactory_NavBarComponent1);
    this._NgFor_26_6 = new import13.NgFor(this._appEl_26.vcRef,this._TemplateRef_26_5,this.parentInjector.get(import19.IterableDiffers),this.ref);
    this._text_27 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_22,'\n\n\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_22,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','nav navbar-nav navbar-right');
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_29,(null as any));
    this._appEl_31 = new import2.AppElement(31,29,this,this._anchor_31);
    this._TemplateRef_31_5 = new import18.TemplateRef_(this._appEl_31,viewFactory_NavBarComponent2);
    this._NgIf_31_6 = new import14.NgIf(this._appEl_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_29,'li',(null as any));
    this._el_34 = this.renderer.createElement(this._el_33,'a',(null as any));
    this.renderer.setElementAttribute(this._el_34,'href','');
    this._text_35 = this.renderer.createText(this._el_34,'Logout',(null as any));
    this._text_36 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._text_37 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_40 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._el_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkWithHref_18_3; }
    if (((token === import18.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import13.NgFor) && (26 === requestNodeIndex))) { return this._NgFor_26_6; }
    if (((token === import18.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import14.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_18_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_18_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = this.context.routes;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_26_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_26_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_26_6.ngDoCheck(); }
    const currVal_4:any = this.context.busyService.isBusy;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_31_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_18_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_18,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_18_3.ngOnDestroy();
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_18_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.logout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_NavBarComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.NavBarComponent> {
  if ((renderType_NavBarComponent === (null as any))) { (renderType_NavBarComponent = viewUtils.createRenderComponentType('C:/Workspace/Frameworks/temphire.angular2/TempHire/app/nav-bar.html',0,import10.ViewEncapsulation.None,styles_NavBarComponent,{})); }
  return new _View_NavBarComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_NavBarComponent1 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import21.RouterLinkActive;
  _query_RouterLink_0_0:import22.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import22.QueryList<any>;
  _el_1:any;
  _RouterLinkWithHref_1_3:import12.RouterLinkWithHref;
  _text_2:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NavBarComponent1,renderType_NavBarComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'routerLinkActive','active');
    this._RouterLinkActive_0_3 = new import21.RouterLinkActive(this.parent.parentInjector.get(import15.Router),new import23.ElementRef(this._el_0),this.renderer);
    this._query_RouterLink_0_0 = new import22.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import22.QueryList<any>();
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_1_3 = new import12.RouterLinkWithHref(this.parent.parentInjector.get(import15.Router),this.parent.parentInjector.get(import16.ActivatedRoute),this.parent.parentInjector.get(import17.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_1_3; }
    if (((token === import21.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._RouterLinkActive_0_3.routerLinkActive = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_2:any = this.context.$implicit.routerLink;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_1_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_1_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset([]);
        this._RouterLinkActive_0_3.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_1_3]);
        this._RouterLinkActive_0_3.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.ngAfterContentInit(); }
    }
    const currVal_3:any = this._RouterLinkWithHref_1_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_1,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.$implicit.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_2,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_1_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NavBarComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NavBarComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_NavBarComponent2 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _el_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NavBarComponent2,renderType_NavBarComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','btn btn-lg btn-warning');
    this.renderer.setElementAttribute(this._el_1,'style','margin-top: 2px');
    this._el_2 = this.renderer.createElement(this._el_1,'span',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','glyphicon glyphicon-refresh glyphicon-refresh-animate');
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._el_2
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_NavBarComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_NavBarComponent2(viewUtils,parentInjector,declarationEl);
}